# -*- coding: utf-8 -*-
# chiour7_fr.srt / .vtt — vidéo w-L3whp2GbI
# Farbrengen Gimmel Tamouz : le maamar "Ve'ata Tetsavé", lien Rabbi/peuple, niveaux de l'âme
VIDEO_END = 1581.6

cues = [
 (0.3,   "Alors, il y a très peu de jours,"),
 (4.9,   "le Rabbi prend un maamar"),
 (8.4,   "qu'il avait dit en 5741,"),
 (13.4,  "1981,"),
 (17.0,  "et il le distribue après de nombreuses années —"),
 (21.3,  "c'est-à-dire que plus de 11 ans s'écoulent."),
 (26.6,  "Or le Rabbi —"),
 (29.5,  "comment recevions-nous les maamarim ? Nous entendions les maamarim du Rabbi, puis, avec le temps,"),
 (35.5,  "on les imprimait, on les trouvait sur les tables de 770, et partout dans le monde on envoyait les fax"),
 (44.9,  "avec le maamar."),
 (46.9,  "Le Rabbi n'avait pas besoin de distribuer le maamar en main propre."),
 (51.4,  "De telles occasions se comptent même sur les doigts d'une main —"),
 (57.1,  "les fois où le Rabbi a remis un maamar en main propre."),
 (60.7,  "Et l'une d'elles, justement —"),
 (63.8,  "nous sommes [à présent]"),
 (66.7,  "à environ 12 jours avant l'attaque (le « stroke ») :"),
 (71.6,  "le Rabbi prend le maamar qu'il avait dit 11 ans plus tôt,"),
 (74.9,  "le reprend et le remet en main propre."),
 (79.6,  "Ce maamar, c'est « Ve'ata Tetsavé » (« Et toi, tu ordonneras les enfants d'Israël ») —"),
 (83.4,  "le rôle de Moché Rabbenou"),
 (86.2,  "dans la génération ; et, bien sûr, dans cette expression, le Zohar et les Tikounei Zohar : « l'extension de Moché (hitpachtouta deMoché) en chaque génération »."),
 (96.0,  "Et à quel point, au fond,"),
 (99.5,  "le lien"),
 (101.1, "entre le peuple d'Israël"),
 (103.4, "et le Nassi hador — et entre le Nassi hador et le peuple d'Israël — est important :"),
 (109.3, "cela, le Rabbi décide de le remettre en main propre, quelques jours avant l'attaque."),
 (117.6, "Ensuite, déjà,"),
 (120.1, "nous n'avons plus pu entendre le Rabbi."),
 (123.2, "Jusqu'à Gimmel Tamouz 5754, nous voyions le Rabbi de temps en temps, mais nous ne l'entendions plus."),
 (130.3, "Et ensuite il y a eu le helem vehester (le voilement)."),
 (133.4, "Et le helem vehester —"),
 (135.4, "celui dont le Rabbi parle —"),
 (139.0, "la sicha célèbre de Youd-Bet Tamouz 5744, où le Rabbi"),
 (143.5, "mentionne en fait le Rogatchover,"),
 (146.6, "qui déduit précisément dans le Yerouchalmi, traité Yoma, que « celui de qui le Beit HaMikdach n'a pas été reconstruit de son vivant, c'est comme s'il avait été détruit de son vivant »."),
 (155.1, "Le Rabbi dit parfois « comme si » ceci ou cela —"),
 (159.2, "c'est comme si cela arrivait maintenant."),
 (161.7, "Le Rabbi soulignait à quel point"),
 (164.8, "un Juif, même au cœur de pierre,"),
 (169.0, "devrait en fait s'émouvoir et crier s'il voyait le Beit HaMikdach détruit à l'instant."),
 (176.4, "Alors,"),
 (177.4, "le sujet des 32 ans après Gimmel Tamouz —"),
 (182.0, "comme nous l'avons dit,"),
 (183.9, "les 32 fois « Elokim » qui figurent dans Béréchit :"),
 (187.2, "ce sont tous les tsimtsoumim nécessaires pour que le monde existe ;"),
 (191.5, "la limite des tsimtsoumim, c'est lamed-bet (lev)."),
 (194.5, "Ainsi, comme nous l'avons dit, les 32 années sont"),
 (199.8, "les 32 fois « Elokim », le voilement du Rabbi, qu'on ne voit pas."),
 (205.2, "Mais,"),
 (206.9, "avec l'aide de D.ieu, tout de suite, immédiatement (tekef oumiyad mamach),"),
 (211.0, "il amènera la Délivrance véritable et complète, à notre tête."),
 (214.8, "Alors, le Rabbi, dans ce maamar —"),
 (219.2, "c'est un maamar sur lequel on peut faire un farbrenguen pendant de nombreux jours, sur chaque lettre, chaque chapitre."),
 (226.3, "Et sur l'un des points —"),
 (228.6, "on sait, comme nous l'avons dit, que l'entreprise de la chli'hout (l'envoi d'émissaires) est née après la révélation de la 'Hassidout."),
 (235.0, "Le regard sur le Juif, avec un tel amour, cela s'est révélé dans la 'Hassidout."),
 (240.4, "De même, le lien entre le Rabbi et le 'hassid :"),
 (245.8, "cette importance"),
 (248.2, "s'est aussi révélée avec la 'Hassidout. Le Hayom Yom le dit aussi explicitement — je crois au 22 Iyar :"),
 (254.8, "autrefois, le Rabbi était seul et les 'hassidim étaient seuls,"),
 (257.4, "et maintenant il y a là un lien très fort. Maintenant, quand nous disons que c'est un 'hidouch de la 'Hassidout,"),
 (261.9, "cela ne veut pas dire que la notion n'a pas toujours existé."),
 (270.1, "La 'Hassidout, en fait, révèle les choses. Elle les met en relief,"),
 (275.6, "elle pose le doigt sur les endroits importants."),
 (280.2, "Par exemple,"),
 (281.7, "il y a la Guemara célèbre dans Sanhedrin, page 8 ;"),
 (285.4, "la Guemara que Rachi cite dans la parachat Vayélekh :"),
 (290.8, "« une seule chose [un seul guide] par génération, et non deux choses par génération »."),
 (294.3, "Il y a un seul Nassi hador, pas deux, pas trois."),
 (299.0, "Il y a aussi ceci :"),
 (301.7, "que le monde entier vit par le mérite du tsaddik — c'est écrit ; pas besoin de prendre le Likoutei Moharan pour cela, c'est écrit dans le Chass,"),
 (312.6, "dans Taanit, page 24 : « le monde n'est sustenté que pour 'Hanina, Mon fils »."),
 (318.4, "Ce sont donc des choses écrites."),
 (320.8, "Mais"),
 (322.4, "ce sujet n'était pas vécu ainsi [si intensément]."),
 (327.6, "On dit que"),
 (331.0, "le roi Salomon, qui était le plus sage de tous,"),
 (336.2, "pour donner une parabole de l'amour du Saint béni soit-Il"),
 (339.4, "pour l'Assemblée d'Israël (Knesset Israël),"),
 (342.0, "n'a pas trouvé de meilleure image que celle de l'homme et la femme (ich ve'icha)."),
 (346.0, "Mais s'il avait vécu après l'époque du Baal Chem Tov,"),
 (349.7, "il aurait donné l'image [du lien] entre le Rabbi et le 'hassid."),
 (355.4, "Car en vérité cela s'est révélé très, très fortement. Mais on ne peut pas contester que c'est vrai : depuis l'époque"),
 (358.8, "du Baal Chem Tov, [puis le Maguid], et ensuite, cette notion"),
 (363.3, "de Rabbi et 'hassid a pris, et a pris"),
 (369.9, "de la force ;"),
 (371.8, "et le don de soi (mesirout nefech) du Rabbi Rayatz — de sorte que les 'hassidim le lui ont rendu par un don de soi, lui ont rendu de l'amour par un don de soi. Mais le lien qu'il y a"),
 (382.8, "aujourd'hui"),
 (384.8, "entre le Rabbi et le peuple d'Israël est un lien"),
 (389.2, "qui, en fait, n'a pas de précédent. Même"),
 (393.0, "les historiens disent — pas besoin d'être 'habad ; tu peux être un historien hérétique —"),
 (399.1, "il te dira qu'à l'époque de Rabbi Yehouda HaNassi, il y avait un homme"),
 (405.4, "qu'on appelait « Rabbi », point. Et tout le monde sait de qui tu parles. Même si tu es un opposant,"),
 (412.6, "et que tu lui dis « le Rabbi a dit », il sait de qui ; même si ce n'est pas un 'habad qui parle, il sait de qui tu parles."),
 (419.2, "Oui, ce lien est un lien puissant."),
 (425.2, "Et en vérité c'est une grande question. L'une des choses qu'on craignait au début, à la révélation de la 'Hassidout,"),
 (433.7, "ce sont les oppositions (hitnagdouyot)."),
 (435.7, "L'une de ces choses, c'était justement ce sujet du Rabbi et du 'hassid ; le Rabbi l'a mentionné plusieurs fois."),
 (442.8, "Mais à plus forte raison, à notre génération, aujourd'hui, Dieu merci, la 'Hassidout"),
 (448.1, "a réussi et est devenue un bien commun. On peut le voir un peu partout — ça a pris."),
 (457.0, "Quand tu écoutes la radio et que le sermon de quelqu'un devient très intéressant, tu sais qu'il y a là un peu de 'Hassidout dedans. Ça a tellement pris,"),
 (468.2, "qu'une fois, à la radio, il y a 15 ans, j'ai entendu quelqu'un dire : « je vais vous raconter une histoire 'hassidique : une fois, le 'Hazon Ich... »"),
 (477.8, "Tant cela a pénétré."),
 (482.5, "Bref,"),
 (486.0, "c'est vraiment une grande question : toi, Dieu merci, si tu as grandi dans la Torah, tu sais étudier le Choulhan Aroukh, tu sais [trancher],"),
 (496.9, "tu accomplis les mitsvot avec soin, tu crains le Ciel —"),
 (500.9, "qu'as-tu besoin de cette chose ?"),
 (505.2, "Le Rabbi, le tsaddik —"),
 (507.7, "pourquoi a-t-on besoin du tsaddik de la génération ? Pourquoi est-ce important ? « Moché en sa génération, Mordekhaï en sa génération comme Moché en la sienne », « l'extension de Moché en chaque génération », comme il est écrit dans le Zohar — pourquoi en a-t-on besoin ?"),
 (519.2, "Le Tanya le résout déjà, dès le chapitre 2."),
 (523.5, "Mais l'un des points que le Rabbi mentionne dans ce maamar « Ve'ata Tetsavé », qu'il a remis juste avant le voilement de Gimmel Tamouz : il voulait qu'il soit clair"),
 (535.0, "que le Rabbi n'est parti nulle part."),
 (538.8, "Car, comme le Rav l'a rappelé, en général tu passes d'un tsaddik à un autre — il y a l'expression"),
 (543.0, "dans la Guemara : « le soleil se lève et le soleil se couche ». Mais Gimmel Tamouz"),
 (545.5, "est le seul jour où le soleil s'est arrêté (chémech beGivon dom), où le soleil ne s'est pas couché ; et c'est lié à Beit Chémech,"),
 (553.8, "car près de Beit Chémech — là où se trouve l'endroit où l'on a étudié — eut lieu la guerre contre les Guivonim, jusqu'à cette région ; des pierres y sont tombées, etc."),
 (570.0, "C'est la région... mais la guerre où Yehochoua a demandé « soleil, à Givon, arrête-toi », c'était dans cette région-là. Bref,"),
 (581.5, "ce qui en ressort,"),
 (583.7, "c'est que le Rabbi, dans le maamar, touche à un point important."),
 (588.6, "Il dit : Moché Rabbenou est appelé le « Ra'aya Mehemna » (le berger fidèle). Dans le saint livre du Zohar,"),
 (597.0, "parachat Naso, il y a une immense section appelée « Ra'aya Mehemna »."),
 (601.6, "Rabbi [Chimon bar Yo'haï], quand il était dans la grotte,"),
 (604.6, "recevait des cours de Torah d'Eliyahou HaNavi ; mais il y a des cours de Torah qu'il a reçus de Moché Rabbenou lui-même,"),
 (610.5, "et cela s'appelle « Ra'aya Mehemna » — tous les enseignements qu'il a reçus directement de Moché Rabbenou."),
 (616.9, "Et pourquoi est-il appelé « berger fidèle » ? Non seulement le tsaddik de la génération, le Moché de chaque génération, est le berger fidèle d'Israël,"),
 (623.6, "mais il est un berger fidèle comme le berger"),
 (628.1, "qui donne à manger au troupeau, aux bêtes."),
 (632.9, "Ainsi, le tsaddik, le Moché Rabbenou de la génération, dont le service est"),
 (638.0, "« ro'éh emouna » (faire paître la foi) :"),
 (640.0, "la nourriture dont il nous nourrit, c'est la emouna (la foi)."),
 (643.6, "Or la foi est le fondement de tout."),
 (646.5, "Maintenant nous sommes dans le sujet de la foi : toute la partie « Lev » du Tanya"),
 (652.5, "ne peut exister sans la foi. Il n'y aura ni amour ni crainte sans la foi, comme le Rabbi l'écrit"),
 (659.4, "dans l'introduction au Chaar HaYi'houd VehaEmouna, « 'Hinoukh Katan » : seulement avec une foi pure. Mais, a priori, qu'as-tu besoin de Moché Rabbenou pour la foi ?"),
 (670.8, "Le peuple d'Israël, comme le dit la Guemara dans Chabbat 97, « sont des croyants, fils de croyants » (maaminim bnei maaminim)."),
 (676.8, "Et dans le maamar « Ve'ata [Tetsavé] », le Rabbi dit quelque chose d'important ; il cite là deux sources."),
 (686.2, "Il dit : pourquoi le peuple d'Israël"),
 (689.4, "croit-il au Saint béni soit-Il de manière simple, sans preuves ? Il n'a pas besoin de preuves ni de démonstrations"),
 (694.2, "que le Saint béni soit-Il existe."),
 (697.2, "Vous savez que les chrétiens sont nombreux ;"),
 (700.0, "il y a des quantités énormes de gens qui croient qu'il y a un Créateur — chacun à sa façon, avec son erreur. Mais comme"),
 (706.7, "le dit le Tsema'h Tsedek dans le « Dérekh Mitsvotekha », [au sujet de] la mitsva de croire en la Divinité, c'est une affaire de connaissance (yedia)."),
 (712.7, "Dans le monde, celui qui a de l'intelligence et n'est pas sot, s'il comprend qu'une chemise ne peut pas se créer, même après une explosion, après des explosions —"),
 (720.4, "ce qui arrive [avec une explosion], c'est seulement de la casse ; on n'a jamais vu que quelque chose de beau se crée d'une explosion ; au contraire,"),
 (727.5, "ça ne fait que tout briser."),
 (729.1, "Mais même s'il y a des explosions, des vagues d'explosions, pendant très, très longtemps, une simple chemise dont les boutons sont alignés selon une mesure précise"),
 (739.3, "ne peut pas se faire toute seule — un monde, c'est bien plus complexe"),
 (744.0, "qu'une chemise. Comme Rabbi Akiva l'a dit à cet homme qui disait « tu ne peux pas savoir qui [a créé le monde] » :"),
 (751.4, "voilà la preuve — il faut être sot pour ne pas croire qu'il y a un Créateur."),
 (754.5, "Tu as des questions, du genre « pourquoi est-ce arrivé ainsi » ? Mais cela n'a aucun rapport avec le fait que tu aies des questions :"),
 (760.2, "il est évident qu'il y a là un Créateur du monde, parfait, immense."),
 (766.1, "Je peux savoir, dès maintenant —"),
 (769.4, "je peux regarder"),
 (771.5, "et voir quand le soleil se lèvera à Beit Chémech en 2035,"),
 (778.4, "et je ne me trompe pas d'une seconde. Vous savez combien de choses doivent fonctionner — ce n'est pas une montre suisse ! — combien de choses doivent tourner dans la galaxie pour que cela arrive,"),
 (789.5, "et elles sont solides « comme aux jours de [la création] » ;"),
 (792.8, "et le soleil arrive à l'heure."),
 (795.7, "Donc tout est réglé de façon prodigieuse."),
 (800.3, "Cela, les non-juifs aussi peuvent le savoir, qu'il y a un Créateur. Mais un Juif, ce n'est pas pour cela qu'il croit qu'il y a un Créateur. Nous, en général, [nous tenons à un niveau plus profond] ;"),
 (810.4, "mais quoi ? Simplement parce qu'on voit la Divinité."),
 (814.8, "Que le Juif [ressente] si simplement qu'il y a D.ieu, c'est parce qu'on voit."),
 (821.0, "Qui voit ? Le Rabbi apporte la Guemara"),
 (824.6, "célèbre dans Meguila, page 3 :"),
 (827.6, "lors de la vision de Daniel, Daniel dit « moi, j'ai vu la vision », et les gens [avec lui] n'ont pas vu la vision,"),
 (834.4, "mais une grande terreur est tombée sur eux. Alors la Guemara demande :"),
 (839.9, "s'ils n'ont pas vu, pourquoi ont-ils eu peur ? — Bien qu'eux n'aient pas vu (af al gav déihou la chazi),"),
 (846.5, "leur mazal a vu (mazlaïhou chazi) : même s'ils n'ont pas vu, leur mazal, lui, [a vu]."),
 (852.0, "L'âme juive a cinq parties."),
 (856.1, "La « part de D.ieu » dont nous avons parlé a cinq niveaux : Nefech,"),
 (860.5, "Roua'h, Nechama, 'Haya, Ye'hida. Le Nefech se revêt dans notre foie,"),
 (867.0, "le Roua'h dans le cœur, du côté droit,"),
 (870.8, "et la Nechama"),
 (872.4, "dans le cerveau."),
 (874.6, "Autour du corps,"),
 (876.1, "il y a la 'Haya, et elle voit aussi des choses d'en haut ; autour du corps, elle se trouve [jusqu'à] quatre amot. C'est la raison pour laquelle, dans le niglé, une personne qui s'approche d'un objet trouvé (metsia) —"),
 (884.5, "si elle a l'intention de l'acquérir seulement [en se baissant], c'est autre chose ; mais si elle veut l'acquérir [par le fait] d'entrer dans ses quatre amot —"),
 (895.8, "comment, à 4 amot, peut-elle acquérir alors qu'elle n'a pas encore saisi l'objet ? Mais sa 'Haya s'étend sur 4 amot autour d'elle, donc elle a [déjà] saisi l'objet."),
 (904.4, "Maintenant, le mazal, c'est le niveau de ce qu'on appelle le « makif hakarov » (l'enveloppe proche) ; c'est en fait une partie de l'âme juive qui se trouve en haut,"),
 (916.9, "et elle voit la Divinité comme nous voyons maintenant"),
 (920.3, "du riz dans l'assiette : elle voit la Divinité."),
 (924.0, "Mais alors, quel rapport ? — Je me trouve ici, mais cette part de 'Haya, c'est la quatrième partie de mon âme, de bas en haut : Nefech, Roua'h, Nechama, 'Haya — et elle aussi"),
 (935.0, "ruisselle en moi. Car il est écrit que chaque jour une voix céleste (bat kol) sort du [mont] 'Horev — le Baal Chem Tov pose la question :"),
 (942.8, "la question s'impose —"),
 (944.3, "à quoi sert-elle si personne ne l'entend ? [Réponse :] on l'entend ;"),
 (947.8, "la 'Haya l'entend. Bon, mais quel rapport avec moi ? Tu vois qu'il y a des gens qui, soudain, en plein milieu de la journée, veulent se renforcer, veulent mieux étudier — d'où cela vient-il ?"),
 (956.7, "Les éveils au repentir (itoroutei techouva), d'où viennent-ils ? À 100 %"),
 (959.9, "— quel rapport ? — c'est la 'Haya. Et la 'Haya, c'est pourquoi on l'appelle « mazal » : mazal, du langage de « nezila » (l'écoulement, le ruissellement)."),
 (966.6, "En Israël, les entrepreneurs du bâtiment ont beaucoup de « nezilot » (fuites). Donc"),
 (970.8, "« mazal » est du langage de l'écoulement — « ruisselant du Liban (nozlim min Levanon) »."),
 (976.2, "Donc l'âme voit en haut et ruisselle [vers le bas] : elle envoie"),
 (979.6, "des e-mails, des WhatsApp ; elle envoie à la partie de l'âme qui est à l'intérieur. Alors le Rabbi, dans ce maamar"),
 (984.0, "« [Ve'ata] Tetsavé », dit : le fait que nous n'ayons pas besoin de preuves"),
 (988.6, "que le Saint béni soit-Il existe — le peuple d'Israël sait qu'il y a la Divinité —"),
 (991.8, "c'est parce que le niveau 'Haya de l'âme voit"),
 (994.2, "la Divinité."),
 (999.2, "Mais il y a encore un sujet, au-dessus de la « vision » :"),
 (1003.0, "il y a en fait encore une partie de l'âme, encore plus élevée, c'est la Ye'hida."),
 (1007.4, "On le dit dans les Hochaanot :"),
 (1011.4, "« Ye'hida leya'hedkha » (l'Unique, pour T'unifier)."),
 (1013.7, "La Ye'hida est unie et unique avec le Saint béni soit-Il ; c'est le « makif harachok » (l'enveloppe lointaine) — c'est très lointain, mais c'est une partie de l'âme reliée à chaque instant à la Divinité."),
 (1023.4, "Et là, c'est une seule chose — cela se relie, comme nous l'avons dit, littéralement « part de D.ieu d'en haut » ; c'est l'essence de l'âme, c'est"),
 (1031.5, "la Ye'hida. Or c'est encore plus fort que la 'Haya. Pourquoi ?"),
 (1037.4, "Parce que la 'Haya,"),
 (1039.2, "en fait, quand tu dis que tu « vois » la Divinité, cela veut dire : il y a le Saint béni soit-Il, et moi, je suis"),
 (1045.7, "un spectateur — comment dit-on ? — un observateur. J'observe, c'est le sens simple. J'observe de l'extérieur ; et parce que j'observe,"),
 (1055.1, "je sais qu'il y a la Divinité. Mais la Ye'hida n'observe pas."),
 (1060.6, "Elle est, là, une seule chose avec le Créateur. Elle est unie au Créateur, reliée au Créateur. Alors, le fait que tu saches qu'Il est là, comme tu sais que toi tu es là —"),
 (1068.0, "tu sais qu'Il est là."),
 (1072.8, "Mais, dit le Rabbi, la seconde manière est bien plus forte. Car souvent, la première manière — comme le dit la Guemara, selon la version du Ein Yaakov, page 63"),
 (1081.4, "de Berachot — [au sujet de] celui qui creuse un tunnel sous une maison [pour voler] et dit « Miséricordieux, sauve-moi ! »."),
 (1085.9, "Le voleur peut demander de l'aide, que D.ieu l'aide à ne pas se faire prendre par la police,"),
 (1091.4, "à attraper un bon butin. Un instant — tu n'as pas besoin d'être un génie pour savoir qu'il est écrit « tu ne voleras pas ». Oui, même les non-juifs l'apprennent. Tout le monde sait"),
 (1101.6, "« tu ne voleras pas », et pourtant tu demandes de l'aide, parce que"),
 (1105.4, "la foi peut rester « makif » (enveloppante, externe) — c'est précisément cela, le « makif » :"),
 (1109.4, "la 'Haya est un makif, donc cela n'agit pas nécessairement en toi-même. Mais la Ye'hida,"),
 (1117.2, "c'est une seule chose ; elle ne peut pas se détacher du Créateur, car c'est en fait toute sa vitalité, tout son être ; et elle n'observe pas, elle ne reçoit pas une information"),
 (1129.6, "externe :"),
 (1131.2, "[ce n'est pas] qu'elle voit la Divinité [de loin] — elle est reliée à la Divinité."),
 (1135.2, "Bon, c'est bien plus puissant. Alors, nous avons tous une Ye'hida ; pourquoi, donc, tout ne coule-t-il pas [parfaitement] dans le judaïsme ? Pourquoi avons-nous des échecs çà et là ? Tout simplement"),
 (1148.2, "parce que le problème, c'est que l'essence de l'âme, parfois,"),
 (1152.1, "est en état de « voilement » (helem) chez nous. Ce que nous ressentons en nous, c'est Nefech-Roua'h-Nechama, et tu ne ressens pas"),
 (1159.7, "l'essence (étsem)."),
 (1163.1, "Maintenant —"),
 (1165.4, "nous avons dit que chacun a un Nefech-Roua'h-Nechama, mais il y a un Nefech collectif (klali). Il y a ton Nefech particulier,"),
 (1173.7, "ton Roua'h, ta Nechama, ta 'Haya et ta Ye'hida particulières. Mais au-delà du tien, il y a un Nefech collectif."),
 (1181.4, "Le Nefech collectif du peuple d'Israël, c'est le roi David. Il y a le Roua'h collectif du peuple d'Israël, qui est Eliyahou HaNavi."),
 (1189.5, "Il y a les [différents] niveaux."),
 (1193.2, "Bref, cela se répartit entre Moché Rabbenou, le roi David, même Adam HaRichon,"),
 (1200.2, "et le Machia'h, etc. Mais, en fin de compte, « l'extension de Moché en chaque génération », c'est aussi la Ye'hida collective"),
 (1204.0, "du peuple d'Israël."),
 (1209.4, "Voilà la différence. Tu dis : quelle différence, pourquoi ai-je besoin d'un tsaddik ? — Il est la Ye'hida collective. C'est un tout autre monde."),
 (1219.2, "C'est comme la question que le [Baal HaTanya] pose dans les derniers chapitres du Likoutei Amarim : le Saint béni soit-Il se trouve partout, « toute la terre est emplie de Sa gloire », « il n'est aucun lieu vide de Lui ». Alors pourquoi sens-tu que la synagogue est plus sainte ?"),
 (1234.0, "Et pourquoi y a-t-il [des degrés de] sainteté ? Il y a, dans le traité Keilim, tous les degrés de sainteté, et l'endroit le plus élevé, c'est le Kodech HaKodachim. Qu'y a-t-il dans le Kodech HaKodachim de plus que dans la rue ?"),
 (1245.3, "Le Saint béni soit-Il se trouve partout."),
 (1247.8, "Mais [c'est] l'une des réponses que le Tanya explique longuement —"),
 (1250.8, "comme la 'Hassidout l'apprend, tirant beaucoup de choses d'Iyov : « de ma chair je verrai D.ieu » (mibessari é'hézé Eloka). L'âme fait vivre tout le corps,"),
 (1258.6, "et l'âme de chacun, ici présent, se trouve dans tout le corps, jusqu'à l'extrémité du pied —"),
 (1266.3, "même là où il y a [comme] une mort dans le corps, le talon : il y a de la vitalité ; et malheur s'il sort de la vitalité, ne serait-ce que d'un ongle ou d'un petit doigt."),
 (1278.2, "Si, à D.ieu ne plaise, il y a là quelque chose et que la vitalité n'y arrive plus, alors, si tu ne coupes pas cette chose,"),
 (1285.6, "cela atteindra tout ton corps."),
 (1288.7, "Tu es vivant"),
 (1290.7, "dans chacun de tes recoins, tout est vivant."),
 (1294.6, "Et pourtant, où chacun ressent-il son âme ? Où ressent-on la conscience ?"),
 (1300.8, "C'est dans le cerveau."),
 (1304.4, "Chacun, quand il sait qu'il est vivant, comprend que tout se passe ici, dans cette boîte [la tête],"),
 (1310.0, "qu'on dit que tout se passe ici."),
 (1313.6, "Et c'est en fait ce que dit le Tanya : c'est le sujet du Kodech HaKodachim. Il est clair que l'âme — comme le Saint béni soit-Il —"),
 (1319.6, "comme le dit la Guemara dans Berachot, page 10 : « de même que le Saint béni soit-Il emplit [le monde], l'âme emplit le corps ; de même que le Saint béni soit-Il porte le monde ». D.ieu est donc l'âme de tous les mondes. Bon, mais où se trouvent la révélation"),
 (1327.2, "et la puissance de la révélation ? Justement dans le cerveau."),
 (1335.4, "Et c'est ce que dit le Tanya au chapitre 2 : nous sommes un seul corps."),
 (1340.3, "Mais le [Chatam] Sofer pose déjà la question : comment vas-tu chez le tsaddik lui demander de prier pour toi auprès du Saint béni soit-Il ? Pourquoi ne vas-tu pas directement ?"),
 (1349.3, "Alors il répond — le Sofer : si ton pied te fait mal, qui va parler au médecin ? Le pied ? Non,"),
 (1356.2, "c'est ta tête. Nous sommes un seul corps. C'est écrit"),
 (1360.0, "dans le Yerouchalmi, oui, que nous sommes un seul corps. Le Yerouchalmi [le dit] pour [enseigner ceci] : si tu te frappes par erreur"),
 (1366.7, "avec le marteau — [si] tu frappes ta main —, tu ne vas pas prendre le marteau dans l'autre main pour la lui rendre [par vengeance], car c'est ton propre corps."),
 (1373.3, "Donc nous sommes un seul corps."),
 (1376.2, "Alors, le sujet du tsaddik,"),
 (1378.8, "du Nassi hador — comme on dit : où est le Kodech HaKodachim ? — on répond : il est à Mezhibuzh [chez le Baal Chem Tov], en quelque sorte."),
 (1387.5, "La révélation"),
 (1389.2, "de la Divinité, en fait, sous la forme la plus forte, se trouve dans le tsaddik. D.ieu se trouve partout, et se trouve"),
 (1395.5, "dans chaque Juif."),
 (1397.4, "Mais de même que dans le corps, dans le cerveau, il y a une révélation bien plus puissante — et là, au moins, on la ressent —, ainsi en est-il"),
 (1404.0, "du tsaddik. Alors le Rabbi, dans « [Ve'ata] Tetsavé »,"),
 (1408.7, "dit :"),
 (1411.1, "pourquoi « l'extension de Moché en chaque génération » est-elle le « berger fidèle » ?"),
 (1415.9, "Il voit avec la foi (ro'éh be'emouna)."),
 (1417.8, "Or nous n'avons pas besoin de cela, nous voyons la Divinité."),
 (1421.9, "Qu'est-ce que « af al gav... chazi » ? Non — mais nous avons dit qu'il y a un niveau bien plus fort. Qu'est-ce que « ihou chazi » ? C'est : tu observes de l'extérieur."),
 (1428.3, "Mais tu n'as pas besoin d'être un observateur extérieur [constatant] qu'il y a un Créateur ; tu dois être avec Lui, vraiment. C'est"),
 (1435.6, "la Ye'hida."),
 (1437.1, "Alors, pourquoi ai-je besoin du Rabbi ? Évidemment que j'ai besoin de lui. Pourquoi ? Parce que [ma Ye'hida] est en état de voilement."),
 (1443.6, "Et le Rabbi dit — le Rabbi écrit dans le maamar « [Ve'ata] Tetsavé » —,"),
 (1448.4, "le Rabbi révèle justement le lien de l'essence (hitkachrout ha'étsem). Comment a-t-il cette capacité ? Parce qu'il est la Ye'hida collective."),
 (1456.6, "Car quel est le point de l'essence de l'âme ? C'est"),
 (1460.0, "la Ye'hida. Et maintenant, quand cela se révèle, ce n'est pas comme le mazal, qui peut être « makif » (externe) et ne pas agir à l'intérieur."),
 (1466.2, "Cela agit à l'intérieur."),
 (1468.2, "Pourquoi cela agit-il à l'intérieur ? Comme le dit le Rabbi dans cette lettre [du maamar] : parce que l'essence de l'âme, c'est l'essence de l'âme qui se trouve dans ton corps."),
 (1477.6, "C'est vraiment l'essence ; c'est pourquoi, là où elle se révèle, toutes tes parties se mettent, en fait, à couler avec elle, et tu ne peux même pas te séparer de la Divinité."),
 (1488.0, "Alors c'est... et comme [le Baal HaTanya] le dit : tout le monde a besoin de lui."),
 (1495.2, "Tout le monde a besoin du Rabbi, tout le monde a besoin de « l'extension de Moché en chaque génération », tout le monde a besoin du « berger [fidèle] » des enfants d'Israël qui [existe] en chaque génération."),
 (1502.6, "Il n'y a pas de question là-dessus. Tu peux être 'hassidique, tu peux être lituanien, peu importe ; la différence — il la dit là, sans entrer dans les détails — c'est si tu le reçois « face à face »"),
 (1515.1, "ou d'une autre manière."),
 (1517.3, "Et nous allons jouer un nigoun ; mais nous verrons que ce n'est pas seulement le spirituel qui passe par le Rabbi —"),
 (1525.1, "même la matérialité de chacun."),
 (1528.8, "Tout vient du Saint béni soit-Il, mais nous verrons pourquoi cela doit passer [par lui]."),
 (1533.5, "Donc, le spirituel, nous l'avons compris : car tout passe par le cerveau,"),
 (1538.0, "et le cerveau donne les ordres et transmet les choses au corps. Mais même la matérialité — qu'est-il écrit"),
 (1545.1, "dans la 'Hassidout ? C'est écrit dans le niglé : « le monde n'est sustenté que pour 'Hanina, Mon fils »."),
 (1551.8, "La manne — comme le dit la Guemara dans Taanit — était par le mérite de Moché ; et finalement tout était par le mérite de Moché : l'eau, la viande..."),
 (1561.7, "Tout passait par Moché. Nous verrons et comprendrons le rapport. Il a déjà un rôle assez grand : nous transmettre le spirituel, nous transmettre la Divinité, pour que nous croyions"),
 (1567.1, "davantage au Créateur, que nous nous reliions davantage au Saint béni soit-Il —"),
 (1569.2, "c'est déjà un grand rôle. Pourquoi ton business, lui aussi,"),
 (1571.6, "doit-il dépendre du tsaddik ? Pourquoi tout le monde est-il sustenté par lui — « 'Hanina, Mon fils » ? Nous comprendrons. Le'haïm, le'haïm !"),
]

def fmt(t, sep):
    h = int(t // 3600); m = int((t % 3600) // 60); s = int(t % 60)
    ms = int(round((t - int(t)) * 1000))
    if ms == 1000: s += 1; ms = 0
    return f"{h:02d}:{m:02d}:{s:02d}{sep}{ms:03d}"

srt, vtt = [], ["WEBVTT", ""]
for i, (start, text) in enumerate(cues):
    end = cues[i+1][0] if i+1 < len(cues) else VIDEO_END
    assert end > start, f"cue {i+1}: end <= start ({start} -> {end})"
    srt += [str(i+1), f"{fmt(start,',')} --> {fmt(end,',')}", text, ""]
    vtt += [f"{fmt(start,'.')} --> {fmt(end,'.')}", text, ""]

open("chiour7_fr.srt", "w", encoding="utf-8").write("\n".join(srt))
open("chiour7_fr.vtt", "w", encoding="utf-8").write("\n".join(vtt))
print(f"OK — {len(cues)} sous-titres écrits (chiour7_fr.srt + chiour7_fr.vtt)")
