# -*- coding: utf-8 -*-
# Génère chiour5_fr.srt + chiour5_fr.vtt — vidéo Rq7Pw7XhgY0
# Farbrengen Gimmel Tamouz : la chlirout, aboutissement de la 'Hassidout ; 'hélek Eloka mima'al
# Fin de chaque cue = début du suivant. Dernier = fin de la vidéo.

VIDEO_END = 951.9

cues = [
 (0.4,   "L'un des 'hidouchim (innovations) —"),
 (3.7,   "le Rabbi a apporté beaucoup de 'hidouchim, et continue d'en apporter au monde."),
 (9.0,   "Mais l'une des choses merveilleuses"),
 (11.9,  "qui s'est produite et continue de se produire dans notre génération,"),
 (16.3,  "c'est l'entreprise de la chlirout (l'envoi d'émissaires)."),
 (20.2,  "Comme on le dit avec humour :"),
 (23.9,  "là où le Coca-Cola n'est pas arrivé,"),
 (28.2,  "Loubavitch est arrivé."),
 (32.2,  "Il faut donc comprendre"),
 (35.0,  "quel est, au fond, le lien"),
 (40.4,  "entre la révélation de la 'Hassidout"),
 (42.9,  "— qui a commencé avec le Baal Chem Tov,"),
 (46.1,  "les générations ayant progressé"),
 (48.4,  "et s'étant complétées l'une l'autre,"),
 (51.0,  "jusqu'à notre génération,"),
 (52.8,  "la septième génération —"),
 (55.1,  "et le fait que la chlirout soit devenue une chose centrale ;"),
 (59.4,  "et pourquoi justement dans notre génération ?"),
 (63.2,  "Si, au fond, c'est lié à la 'Hassidout,"),
 (66.7,  "alors pourquoi"),
 (69.0,  "cela a-t-il commencé [seulement maintenant] ?"),
 (70.8,  "Le 12-13 Tamouz symbolise le don de soi (mesirout nefech) pour la diffusion de la Torah ; mais l'entreprise de la chlirout,"),
 (80.4,  "telle qu'elle est, sans égale,"),
 (83.2,  "c'est justement dans notre génération."),
 (88.6,  "D'où [vient-elle] ?"),
 (93.0,  "C'est justement à nous de comprendre pourquoi."),
 (96.8,  "Alors, en fait,"),
 (100.2, "l'une des choses"),
 (102.5, "que la 'Hassidout"),
 (105.1, "a révélées,"),
 (106.8, "et en particulier élucidées (biror)"),
 (109.4, "sous la forme de 'Habad — 'Hokhma, Bina, Daat —,"),
 (114.2, "c'est ce qui est écrit dans le Zohar :"),
 (117.5, "« la Torah,"),
 (119.0, "Israël et le Saint béni soit-Il sont un »."),
 (123.2, "La notion"),
 (124.9, "d'« une part de D.ieu d'en haut, littéralement » ('hélek Eloka mima'al mamach)"),
 (133.6, "est en fait"),
 (135.9, "expliquée dans le Tanya."),
 (139.2, "En effet,"),
 (142.3, "« 'hélek Eloka mima'al » est un verset dans Iyov (Job)."),
 (145.7, "Le sens simple du verset dit"),
 (149.0, "que chaque homme a sa part dans le monde : celui-ci sera riche, celui-là épousera untel,"),
 (156.7, "il aura tant de maisons, de rues, il demeurera"),
 (160.8, "ici ou là. Ça, c'est le sens simple (pchat)."),
 (164.8, "Chacun a une « part de D.ieu d'en haut » : il a la part"),
 (168.3, "que D.ieu a décidée — quel business, quel argent, quelle"),
 (172.2, "épouse, quels enfants — voilà la « part de D.ieu d'en haut »."),
 (177.1, "Mais dans le Tanya,"),
 (179.8, "et comme on pouvait déjà le voir autrefois"),
 (182.0, "dans le Maharcha, page 32 du traité Chabbat, dans les aggadot,"),
 (187.3, "ainsi que dans le Pnei Yehochoua,"),
 (190.1, "au chapitre 2, page 38 : on peut comprendre « une part de D.ieu »"),
 (195.2, "au sens où nous sommes une partie du Saint béni soit-Il. Mais"),
 (198.8, "dans la 'Hassidout, c'est expliqué — enfin ! — de la manière la plus claire : il y a un Créateur (Boré) et il y a des créatures (nivraïm)."),
 (207.4, "Avant la création du monde, comme il est dit dans les Pirkei deRabbi Eliezer,"),
 (211.8, "« Il était, Lui et Son Nom seuls » — il n'y avait que le Saint béni soit-Il,"),
 (215.2, "Lui et la lumière de Son essence, la lumière infinie (Or Ein Sof) — selon le langage de l'Arizal —, qui emplissait tout l'espace."),
 (223.7, "En mots simples : il n'y avait que le Saint béni soit-Il. Ensuite, D.ieu a créé le monde [à partir] d'une sorte de néant ; et pas seulement"),
 (230.7, "le monde, mais tous les mondes intermédiaires, toute la chaîne descendante (histalchelout)."),
 (236.3, "Tout, c'est D.ieu qui l'a créé. Cela, ce sont des créatures."),
 (241.1, "Les nations sont des créatures,"),
 (243.5, "les anges sont des créatures,"),
 (246.0, "les animaux sont des créatures, les pierres sont des créatures."),
 (250.4, "Mais l'âme (nechama) d'un Juif n'est pas une partie des créatures :"),
 (256.6, "elle est une partie du Créateur."),
 (259.2, "C'est cela le sens d'« une part de D.ieu d'en haut »."),
 (262.9, "C'est comme le fils, qui provient de l'esprit (moa'h) de son père."),
 (266.2, "Tu es une partie du Saint béni soit-Il. L'ange est une créature"),
 (270.5, "du Saint béni soit-Il, et l'âme juive est une partie"),
 (273.8, "du Saint béni soit-Il."),
 (276.0, "C'est l'a-b-c, c'est ce que le Tanya dit déjà au chapitre 2."),
 (282.1, "Or cela change beaucoup de choses."),
 (286.0, "De même, la Torah et le Saint béni soit-Il sont un :"),
 (289.5, "Lui et Sa sagesse sont un — ou, dans le langage du Rambam, « Il est le Connaissant, le connu et la connaissance », etc."),
 (295.4, "La Torah et le Saint béni soit-Il sont une seule chose,"),
 (298.7, "et Israël, le Saint béni soit-Il et la Torah sont une seule chose ; toute la division survient plus loin,"),
 (305.3, "dans la chaîne descendante (histalchelout)."),
 (308.3, "Du coup,"),
 (310.3, "la 'Hassidout"),
 (312.2, "a fait une révolution."),
 (314.9, "Le fait que tu aies une telle [estime pour] Israël — tiens, le Hayom Yom d'aujourd'hui était lié à l'amour d'Israël (ahavat Israël) —,"),
 (321.3, "le fait que l'amour d'Israël soit si développé"),
 (324.4, "dans la 'Hassidout,"),
 (327.3, "cela provient"),
 (329.3, "de la révélation de la 'Hassidout : que tu saches que le Juif est"),
 (332.7, "une partie du Créateur."),
 (334.6, "Même s'il a une kippa ou pas de kippa,"),
 (338.8, "comme il est écrit dans la Michna : « bien qu'il ait fauté, il [reste] Israël » — avec kippa, sans kippa, avec un anneau au nez ou non,"),
 (345.5, "il est une part de D.ieu d'en haut."),
 (348.6, "Une partie du Créateur, au-dessus des anges, au-dessus de tout,"),
 (353.1, "au-dessus de toute l'énergie que D.ieu a mise dans la création du monde et dans toute la galaxie — [tout cela] rien que dans un seul Juif. Alors tu"),
 (360.2, "le regardes autrement. Et même quand tu lui parles,"),
 (365.5, "tu crois que tu peux réussir,"),
 (368.2, "car tu sais qu'il y a là quelqu'un qui entend. Il y a là"),
 (372.2, "une connexion, un wifi : il entend, il y a une connexion."),
 (377.0, "Donc, non seulement cela nous a aidés — [savoir] que c'est une part de D.ieu d'en haut, [savoir] comment regarder un Juif :"),
 (386.4, "comme l'émissaire en chef, le Rabbi en personne."),
 (394.2, "Voilà."),
 (396.0, "Donc, non seulement il y a une « part de D.ieu d'en haut »"),
 (400.7, "et « la Torah, Israël et le Saint béni soit-Il sont un » — et la 'Hassidout l'a clarifié en long et en large —,"),
 (409.5, "c'est aussi la raison"),
 (411.9, "qui a engendré l'essor et la puissance de la chlirout. La 'Hassidout,"),
 (416.7, "en fait,"),
 (418.5, "sa révélation ne nous a pas seulement appris comment regarder un Juif,"),
 (424.5, "comment croire que le Juif, même s'il paraît éloigné, a"),
 (428.7, "en lui une part de D.ieu d'en haut :"),
 (432.0, "il n'est pas de la catégorie des anges — qui font partie des créatures —,"),
 (435.6, "le Juif fait partie du Créateur."),
 (439.0, "Donc ce n'est pas seulement un autre regard sur le Juif, mais bien plus que cela."),
 (444.1, "Le peuple d'Israël, avant la 'Hassidout —"),
 (446.6, "comment voyait-il les choses, au fond ?"),
 (450.5, "Il y a un Créateur et il y a des créatures, et tu penses que tu fais"),
 (455.6, "partie des créatures,"),
 (457.9, "que tu fais partie des ouvriers."),
 (460.9, "Le Créateur a un grand business, et Il a un objectif pour ce business : Il veut le mener pour en tirer"),
 (468.1, "de grands profits,"),
 (470.9, "et toi, tu travailles dans Son business — mais c'est Son business à Lui."),
 (476.8, "En effet, quand tu es un Juif, avant de faire le Kriat Chéma au coucher, tu es censé faire un examen de conscience ('hechbon nefech)."),
 (484.1, "Au moins à Eloul, on le fait. Alors, qu'est-ce que cet examen de conscience ?"),
 (489.8, "Prends ta vie à toi —"),
 (492.4, "ta femme, tes enfants, ton argent,"),
 (497.6, "ta voiture : tout cela, c'est ta vie. Mais ici, on ne parle pas de ta vie ; maintenant on parle de ce que tu"),
 (504.8, "fais pour le business du Créateur."),
 (507.8, "Par exemple,"),
 (510.0, "tu arrives au Kriat Chéma du coucher, tu regardes ta journée et tu dis : faisons un « ✓ ». Sur quoi ?"),
 (518.5, "Pas sur mon propre dossier — pas besoin de l'examiner ; je prends le dossier du Créateur, Son business. Moi, j'ai mon propre business,"),
 (526.5, "j'ai ma propre vie ; mais il y a là le business du Créateur. Et alors, que fait le Juif ? Il coche, il dit :"),
 (534.5, "j'ai dit les bénédictions du matin, oui ;"),
 (538.0, "j'ai mangé, je me suis lavé les mains et j'ai dit le Birkat Hamazon après le repas, bon ; j'ai prié, j'ai prié avec le quorum (minyan), bon ;"),
 (547.3, "Min'ha, quoi encore... Alors un bon Juif en fera plein, et"),
 (550.9, "le soir il est tranquille, [il dit au] Saint béni soit-Il : ce que"),
 (556.0, "Tu m'as imposé de faire pour Toi, voilà, c'est là, je l'ai fait"),
 (560.4, "pour Toi, bien. Il y a peut-être des choses à améliorer, mais voilà l'essentiel."),
 (565.9, "Cela, c'était avant que la 'Hassidout ne se révèle."),
 (570.2, "La 'Hassidout, qu'a-t-elle révélé ?"),
 (573.8, "Qu'en réalité,"),
 (576.8, "tu es un associé (choutaf)."),
 (578.9, "Tu n'es pas un simple ouvrier."),
 (581.3, "À quoi cela ressemble-t-il ? Tu es plutôt [comme]... un homme a un grand business — la même histoire que tout à l'heure —, mais qui y travaille ? Le fils."),
 (591.2, "Le fils est dans l'entreprise et il s'en soucie, car la réussite de l'entreprise du père est sa réussite à lui."),
 (598.4, "Car le fils hérite de tout — même un nourrisson d'un jour hérite de tout."),
 (603.8, "Donc le business est une affaire familiale."),
 (608.8, "La 'Hassidout,"),
 (611.4, "avec toutes ses révélations, toutes ses explications, du point de vue de la 'Hassidout 'Habad — avec l'intellect, avec 'Habad —,"),
 (618.9, "qu'a-t-elle fait ? Elle t'a fait comprendre que la Torah n'est pas un mal de tête imposé :"),
 (626.0, "c'est toi. Tu es indissociable de celui qui s'occupe de la Torah, car c'est ta vie — « car c'est elle notre vie et la longueur de nos jours ». Tu fais partie de l'histoire. C'est de la Divinité, et c'est de la Divinité."),
 (637.4, "Donc, en fait, le business, ce n'est pas « qu'as-tu fait pour Son business » : c'est mon business à moi."),
 (645.0, "C'est pourquoi, quand tu vois les choses ainsi, il en ressort que tu ne peux pas dire : « j'habite maintenant à [tel] niveau,"),
 (653.9, "j'habite à Bnei Brak, j'élève mes enfants, et, D.ieu merci, c'est déjà beau si, après 120 ans, je peux dire :"),
 (667.2, "D.ieu, j'ai élevé des fils et des petits-fils qui s'occupent de Torah et de mitsvot — waouh ! »"),
 (672.7, "Mais un 'hassid qui étudie la 'Hassidout ne s'est pas contenté de cela."),
 (677.2, "Pourquoi ? Parce qu'il y a là encore plein de Juifs qui ont besoin de se réveiller. Il y a beaucoup à faire. — Mais qu'est-ce que ça peut te faire ?"),
 (686.2, "[Parce que] c'est toi. Celui qui ne fera pas de travail de chlirout,"),
 (692.1, "qui ne se souciera pas d'une famille éloignée, ne se souciera pas, en fait,"),
 (697.9, "d'un Juif de plus qui mette les téfilines, d'un Juif de plus qui inscrive ses enfants à l'étude de la Torah —"),
 (703.2, "tu arriveras après 120 ans là-haut et tu recevras une punition. Non pas parce que tu cocheras « tout ce que D.ieu m'a dit, je l'ai fait »,"),
 (713.0, "mais parce que tu regardes [cela] comme étant Son business à Lui. Alors tu es l'ouvrier : quand il termine, il ferme la boutique — peu lui importe de rester même s'il reste un client ;"),
 (723.8, "mais le fils, pour qui c'est sa propre entreprise, fait des heures supplémentaires."),
 (730.2, "Et voilà tout le sujet de la 'Hassidout."),
 (732.9, "La 'Hassidout et la chlirout vont de pair : quand tu comprends que tu es une partie du Créateur, tu comprends que tu es"),
 (739.8, "un associé. C'est pourquoi, après que la 'Hassidout s'est révélée au fil de toutes les générations, la chlirout en est une conséquence. Mais"),
 (748.6, "qu'y avait-il [d'abord] ? Un monde qui n'y était pas prêt,"),
 (753.0, "matériellement."),
 (754.9, "Même si le Rabbi Rayatz a fait là-bas un don de soi pour la diffusion de la Torah, jusqu'où peux-tu influencer ?"),
 (761.3, "Jusqu'où peux-tu envoyer des émissaires dans toutes les régions du monde, sur les cinq continents ?"),
 (767.7, "Jusqu'où en as-tu les capacités ? Les capacités"),
 (773.6, "— et toute la modernisation du monde — se sont développées"),
 (778.5, "surtout"),
 (780.1, "à la génération du Rabbi. Cela a commencé il y a 200 ans, toutes sortes de découvertes, et ça file. Mais ce qui s'est passé à notre génération,"),
 (788.0, "c'est que maintenant on peut faire un farbrenguen et qu'on peut nous voir ailleurs,"),
 (793.7, "et qu'ensuite tu peux avoir mille vues : toutes ces capacités se sont développées à la septième génération."),
 (801.5, "Et l'on ne peut pas non plus prendre des gens qui n'étudient qu'occasionnellement un petit vort (une parole)"),
 (810.0, "de 'Hassidout, et penser qu'ils seront [pour autant] convaincus,"),
 (815.0, "qu'ils vivront ses messages et réussiront à transformer le monde pour le Saint béni soit-Il — parce que c'est ton business —, ça ne marche pas si facilement : il faut grandir"),
 (823.9, "avec cela. Et c'est précisément [le rôle de] la yéchiva Tom'hei Temimim, depuis que le Rabbi Rachab l'a créée. C'était la conception (hachkafa) de la 'Hassidout"),
 (833.5, "révélée depuis le Baal Chem Tov, en particulier depuis l'Admour Hazaken, puis nos maîtres ; mais ensuite il fallait des soldats,"),
 (842.1, "des soldats de la maison de David."),
 (843.7, "C'est Tom'hei Temimim. Bon, tu as maintenant un commando : il te faut des avions, il te faut des moyens"),
 (853.1, "pour les faire voler. Et cela s'est créé — c'est une histoire, un processus qui a commencé avec le Rabbi, et cela arrive, et c'est arrivé"),
 (862.6, "à notre génération, la septième, à la génération du Rabbi. Et le Rabbi a pris toute la conception de la 'Hassidout, et a pris les soldats"),
 (870.4, "de Tom'hei Temimim que le Rabbi Rachab avait formés,"),
 (874.3, "et les a envoyés en chaque lieu."),
 (877.2, "C'est pourquoi, lorsqu'on se trouve"),
 (879.3, "à Gimmel Tamouz,"),
 (881.9, "nous devons nous rappeler la chose la plus importante pour le Rabbi aujourd'hui : c'est son entreprise de la chlirout. Et chaque Juif"),
 (891.9, "doit, en fait, se sentir [investi d'une] chlirout."),
 (895.0, "Cela n'a rien à voir [avec le statut] : le Rabbi a vu en chacun un émissaire (chalia'h). Tu es à la Knesset — tu es un chalia'h ; tu es de gauche, tu écris dans le journal — tu es un chalia'h."),
 (901.3, "Transmets des messages. Tout le monde doit servir"),
 (905.1, "le Créateur ici"),
 (907.7, "et se soucier du peuple d'Israël. Alors, renforçons-nous aujourd'hui,"),
 (911.4, "avec l'aide de D.ieu, dans l'une des choses merveilleuses qu'a accomplies"),
 (915.7, "le Rabbi à notre génération. C'est, en fait, le fruit de toute la 'Hassidout, de toute l'entreprise, et de tous les Temimim qui ont été formés."),
 (922.0, "Et D.ieu lui a donné la possibilité, en cette génération, d'agir, et il continue d'agir. Et nous, nous aiderons. Le Rabbi dit :"),
 (925.4, "« j'ai besoin de mes fils. » Il a besoin de nous pour l'aider,"),
 (932.2, "afin d'achever ce qu'il a dit dans son tout premier maamar : que le but est de faire descendre la Chékhina concrètement, dans les faits (befoal mamach)."),
 (939.2, "Car tant que cela ne s'est pas produit concrètement, dans les faits, le Rabbi appelle cela « vanité et néant » (hevel varik). Alors, avec l'aide de D.ieu,"),
 (946.8, "nous l'aiderons pour que cela se réalise concrètement. Le'haïm,"),
 (948.6, "le'haïm. Amen."),
]

def fmt(t, sep):
    h = int(t // 3600)
    m = int((t % 3600) // 60)
    s = int(t % 60)
    ms = int(round((t - int(t)) * 1000))
    if ms == 1000:
        s += 1; ms = 0
    return f"{h:02d}:{m:02d}:{s:02d}{sep}{ms:03d}"

srt, vtt = [], ["WEBVTT", ""]
for i, (start, text) in enumerate(cues):
    end = cues[i+1][0] if i+1 < len(cues) else VIDEO_END
    assert end > start, f"cue {i+1}: end <= start ({start} -> {end})"
    srt.append(str(i+1))
    srt.append(f"{fmt(start,',')} --> {fmt(end,',')}")
    srt.append(text)
    srt.append("")
    vtt.append(f"{fmt(start,'.')} --> {fmt(end,'.')}")
    vtt.append(text)
    vtt.append("")

open("chiour5_fr.srt", "w", encoding="utf-8").write("\n".join(srt))
open("chiour5_fr.vtt", "w", encoding="utf-8").write("\n".join(vtt))
print(f"OK — {len(cues)} sous-titres écrits (chiour5_fr.srt + chiour5_fr.vtt)")
