# -*- coding: utf-8 -*-
# Génère chiour4_fr.srt + chiour4_fr.vtt — vidéo LedONs5UYFw
# Suite Hilkhot Mouktsé : tiltoul min hatsad / begufo / derrière la main (CA HaRav 309-311, 276)
# Fin de chaque cue = début du suivant. Dernier = fin de la vidéo.

VIDEO_END = 1330.6

cues = [
 (0.4,    "Alors, premièrement,"),
 (3.5,    "nous avons vu la différence entre le tiltoul min hatsad (le déplacement indirect)"),
 (7.2,    "et le tiltoul begufo (le déplacement avec son corps). Maintenant, ne pas s'embrouiller : il arrive parfois"),
 (10.3,   "que ce qui est, dans les faits, un tiltoul begufo soit appelé, dans la halakha, tiltoul min hatsad."),
 (14.2,   "Oui — il y a Rachi, et parfois aussi l'Admour Hazaken commence par appeler le déplacement « derrière les mains » (mé'a'horei yadav) un tiltoul min hatsad,"),
 (21.5,   "mais à la fin, au cœur du propos, on voit qu'il l'appelle un véritable tiltoul begufo. Mais,"),
 (29.6,   "en principe, on fait la distinction."),
 (31.8,   "Il y a un déplacement comme aux simanim 309-310 : une chose sur laquelle il y a du mouktsé,"),
 (37.1,   "une chose qui n'est pas devenue « support » (bassis), car le mouktsé n'y a pas été posé"),
 (40.0,   "— ni à l'entrée du Chabbat (bein hachemachot), ni posé là intentionnellement pour y rester ; on a oublié, etc. —"),
 (42.5,   "alors, quand tu déplaces l'assiette sur laquelle il y a des coquilles de noix ou des choses pareilles,"),
 (46.8,   "de cela nous avons parlé : déplacer pour le besoin du mouktsé est interdit."),
 (55.8,   "Mais si c'est pour le besoin de l'emplacement lui-même,"),
 (60.4,   "ou que tu en as besoin pour autre chose et que tu ne peux pas le déplacer sur place parce que tu as besoin de cet endroit,"),
 (64.4,   "ou qu'il y a un fruit, comme une figue, qui pourrait se salir au sol — alors tu ne vides pas les coquilles de noix séparément —,"),
 (71.4,   "il y a des permissions de déplacer ; mais pas pour le besoin du mouktsé. Tu ne peux pas prendre"),
 (78.2,   "une assiette sur laquelle il y a du mouktsé complet et la déplacer pour le besoin du mouktsé, parce que tu veux ce mouktsé-là."),
 (86.6,   "Mais Rabbenou Yona et les Richonim soutiennent : ceci est un tiltoul min hatsad — par le moyen d'autre chose. En revanche, le tiltoul begufo"),
 (97.7,   "est en fait permis même pour le besoin du mouktsé. Ainsi le dit Rabbenou Yona. Il y a des Richonim qui contestent : le Ran dit que non."),
 (106.5,  "Le Ran dit qu'il est interdit de déplacer du mouktsé avec son corps (begufo) pour le besoin du mouktsé. Oui — parfois il y a des permissions"),
 (110.3,  "particulières qu'on t'accorde parce que c'est une grosse perte et qu'une personne pourrait s'affoler pour son argent. Mais"),
 (117.7,  "en principe, tu ne déplaces pas le mouktsé, même de manière inhabituelle (bechinouï). Tu crains que ta caméra s'abîme, ou un objet cher,"),
 (124.7,  "tu te dis « je vais la prendre autrement (bechinouï) » — il y en a un, le Ran, qui dit que c'est interdit. Mais en pratique, le Choulhan Aroukh, et aussi"),
 (130.8,  "l'Admour Hazaken, ont tranché qu'on peut déplacer du mouktsé pour le besoin du mouktsé si c'est begufo. Maintenant, l'âme"),
 (144.4,  "de cette permission : les A'haronim se demandent — est-ce que l'idée, c'est parce que c'est bechinouï (inhabituel) ?"),
 (150.6,  "Sommes-nous enclins à faire facilement des interdits rabbiniques dès lors que c'est bechinouï ? On a vu une chose pareille pour le besoin d'un malade,"),
 (157.5,  "parfois, toutes sortes de choses ; mais faire des choses ordinaires bechinouï — non. Ce n'est pas à cause du chinouï."),
 (164.4,  "Il y a donc la sougia"),
 (167.1,  "du tiltoul begufo ; elle a plusieurs sources dans le Chass."),
 (171.5,  "Il y en a une..."),
 (173.6,  "il y en a une dans le traité Baba Kama,"),
 (176.4,  "il y en a une — quand tu es assis sur la paille — et un peu avant cela,"),
 (185.3,  "tu as du mouktsé."),
 (187.7,  "Quelle page est-ce ? 127. À la page 127, il y a [un cas de] mouktsé : parfois tu entres comme dans un débarras,"),
 (193.6,  "et là tu as toutes sortes de choses qui sont mouktsé, et tu veux simplement pousser ces choses pour atteindre [ce dont tu as besoin]. Alors Rachi —"),
 (205.0,  "il y a un Rachi à la page 127a,"),
 (208.8,  "au dibour hamat'hil « ber'glo » — écrit là"),
 (213.2,  "dans quel cas cela ne s'appelle pas un « déplacement » (tiltoul). Voyez la formulation : il en a une autre sur laquelle le 'Hazon Ich bâtit tout un système."),
 (219.9,  "Le 'Hazon Ich a une rigueur ('humra) très grande dans cette affaire, car là il apparaît que cela se déplace incidemment, au passage, sans que tu vises la chose."),
 (228.8,  "Mais si nous tenons à cette précision dans ce Rachi, c'est à cause d'autres sougiot dans Baba Kama, à d'autres endroits,"),
 (235.3,  "[montrant] que, dans le tiltoul begufo, on peut déplacer le mouktsé intentionnellement, et pour le besoin du mouktsé. Oui, c'est possible. Telle est"),
 (243.6,  "la conclusion."),
 (245.6,  "Maintenant, le 'Hazon Ich lui dira — le 'Hazon Ich lui dit — que toi, tu déplaces du mouktsé carrément"),
 (251.6,  "bechinouï : cela n'existe pas. Comme s'il n'y avait plus de [permission] begufo pour le besoin du mouktsé,"),
 (258.0,  "et de plus quand tu vises à le déplacer. Non. [Le cas permis,] c'est de manière incidente, en marchant, sur ton chemin,"),
 (265.1,  "et au passage — il n'apparaît pas que tu le vises — tu pousses un peu en marchant ; mais que ce soit visé et que cela paraisse visé, le 'Hazon Ich est strict là-dessus. Mais"),
 (276.0,  "sache que, même chez les Lituaniens, peu ont adopté cette rigueur. En revanche,"),
 (284.0,  "le déplacement begufo est en fait permis, même pour le besoin du mouktsé."),
 (291.4,  "Alors, qu'est-ce que « le besoin du mouktsé » ? Pour qu'il ne soit pas volé."),
 (295.3,  "Oui ? Pour qu'il ne s'abîme pas — tu ne veux pas perdre la caméra, c'est une perte d'argent. Alors tu la déplaceras bechinouï et la mettras à un endroit normal."),
 (304.0,  "C'est permis."),
 (306.0,  "La question, en fait,"),
 (308.2,  "c'est si ce n'est pas pour un besoin du tout."),
 (312.6,  "Alors, chez l'Admour Hazaken, il n'est pas écrit"),
 (317.9,  "clairement que ce serait permis sans aucun besoin. Au siman 308 non plus, le Maguen Avraham ne l'écrit pas explicitement. Seulement, les exemples"),
 (325.0,  "apportés sont ceux qu'on a permis, comme on le dit au siman 308 et au siman 311 : à la fin des exemples apportés, [montrant] que tu peux déplacer"),
 (336.7,  "begufo pour le besoin du mouktsé,"),
 (340.3,  "ces exemples — qu'est-ce que « le besoin du mouktsé » ? Pour qu'il ne soit pas volé, qu'il ne s'abîme pas — donc, malgré tout, un besoin quelconque,"),
 (348.4,  "ou pour le confort de la position assise."),
 (352.2,  "Or, justement sur la formule du « confort de la position assise », là, dans le Maguen Avraham, à l'alinéa — je crois, oui, l'alinéa..."),
 (358.6,  "— il y a là le... pardon, non, c'est plus court, l'alinéa... —"),
 (368.2,  "il y a le Ma'hatzit HaShekel. Il écrit que le Maguen Avraham souligne que c'est pour le besoin du confort que tu déplaces la paille avec ton corps ; et alors il dit : voilà que c'est pour un besoin. Mais si"),
 (380.6,  "ce n'est pas pour un besoin du tout,"),
 (382.7,  "c'est un problème. C'est la précision du Ma'hatzit HaShekel sur le Maguen Avraham. Maintenant, cela dépend peut-être, en réalité, d'une 'hakira (investigation)."),
 (391.0,  "Parmi les compilateurs, tous l'ont repris et ont dit : tu peux déplacer le mouktsé pour le besoin du mouktsé, begufo,"),
 (399.8,  "pour qu'il ne soit pas volé, qu'il ne s'abîme pas, ou pour un autre besoin du mouktsé. Mais pas sans aucun besoin. Une personne, simplement,"),
 (408.2,  "a une pièce de monnaie au milieu de la pièce, par terre ; elle veut juste faire comme un match de foot avec —"),
 (414.1,  "pas que tu veuilles la cacher parce que tu crains qu'un enfant la mette à la bouche, ou qu'on te vole le billet. On parle donc d'un cas où il y a un besoin, [par opposition à] sans besoin."),
 (424.8,  "En général, donc, c'est admis. Mais en vérité il y a une 'hakira : certains disent — pourquoi est-ce permis ? Ce n'est pas du fait du chinouï,"),
 (434.0,  "mais du fait que cela ne s'appelle pas un « tiltoul », dit Rachi."),
 (439.0,  "Alors, si cela ne s'appelle pas un tiltoul, qu'est-ce que ça change ?"),
 (443.1,  "Oui. Donc le fait qu'ils aient écrit « pour le besoin du mouktsé »,"),
 (448.1,  "ce n'est pas pour énoncer une rigueur. On peut dire l'inverse :"),
 (451.8,  "c'est pour dire que même pour le besoin du mouktsé — ce qui, dans le tiltoul min hatsad, est interdit pour le besoin du mouktsé —, il y a beaucoup de cas où,"),
 (460.6,  "pour son usage et pour sa place, c'est permis ; mais"),
 (464.5,  "parfois, quand tu te soucies du mouktsé lui-même — pour qu'il ne soit pas volé —, c'est interdit [dans le min hatsad]. Oui."),
 (471.2,  "Donc ici on innove que begufo c'est permis pour le besoin du mouktsé."),
 (475.8,  "Mais quelle est la différence entre « pour le besoin du mouktsé » et pas pour un besoin du tout, juste pour jouer ? Car si cela ne s'appelle pas"),
 (481.1,  "un tiltoul, cela ne s'appelle pas un tiltoul ! Donc cela ne prouve pas, en fait, la chose [la rigueur],"),
 (485.2,  "même si, sur les détails, la plupart ont suivi le Ma'hatzit HaShekel. Et tu peux dire, par rigueur : d'accord, nous n'avons pas trouvé"),
 (496.4,  "de manière explicite"),
 (498.4,  "une permission pour ce qui est vraiment, vraiment sans aucun besoin."),
 (502.7,  "Ce n'est pas écrit explicitement. Les exemples sont des exemples ; il n'y en a pas d'autre que « pour qu'il ne soit pas volé » ou « pour le confort »."),
 (510.1,  "Oui. Mais quand même, celui qui dit que..."),
 (514.3,  "— il y en a qui ont voulu dire qu'il y a ici quelque chose de plus particulier, à cause du chinouï."),
 (518.9,  "Et de là on arrive à une rigueur supplémentaire. Voyez par vous-mêmes : si une personne a"),
 (527.6,  "du mouktsé"),
 (529.3,  "dans sa chemise — oui, je dis exprès « dans la chemise » —,"),
 (533.2,  "[hum] parce que la chemise,"),
 (535.6,  "[par opposition à] une poche de pantalon ou de veste — nous avons dit au siman [310] que le vêtement n'est pas tafel (subordonné) à la poche, donc"),
 (546.2,  "là il n'y a pas de problème. Mais justement un endroit où il y a bien un problème, oui ? Ou la manière dont la personne a coutume de mettre un porte-monnaie"),
 (557.5,  "accroché à la ceinture — c'est à examiner — ou ici, où il y a bien un problème. Mais là, c'est la façon [habituelle] de déplacer :"),
 (565.7,  "déplacer à l'intérieur de la poche, ce n'est pas un chinouï. Alors, est-ce que cela s'appelle begufo, ou pas begufo ?"),
 (572.1,  "Il y a beaucoup d'A'haronim qui sont stricts là-dessus, qui disent : cela s'appelle un tiltoul beguf, pas un tiltoul begufo. Le tiltoul begufo, c'est quand ce n'est pas la manière [habituelle] —"),
 (582.3,  "[hum]"),
 (582.4,  "ce n'est pas la façon de déplacer"),
 (586.0,  "le mouktsé, en fait, avec le pied."),
 (589.7,  "Au passage : tu as une pierre qui maintient une porte et qu'on ne déplacera jamais —"),
 (596.9,  "il est interdit de la déplacer, cette pierre. Il y a donc beaucoup d'A'haronim qui sont stricts là-dessus — énormément de compilateurs le sont aussi —, qui disent que si tu déplaces le mouktsé pour le besoin du mouktsé"),
 (610.8,  "d'une manière qui est la façon [habituelle] de déplacer une pierre pour caler une porte — parfois avec le pied —, alors ils disent : si c'est la manière [habituelle],"),
 (619.8,  "ici tu n'as pas son [statut de] begufo."),
 (622.8,  "Mais en pratique, après tous les pilpoulim — faites toutes les précisions que vous voulez —, prenez [le siman 311] au séif 19 :"),
 (628.4,  "oui, après tous les pilpoulim, même dans le Kountrass A'haron,"),
 (634.4,  "on est indulgent là-dessus."),
 (636.6,  "Voyez à un endroit où il apporte parfois — il y a un cas où l'on apporte"),
 (642.0,  "deux raisons, pour concilier aussi celui qui ne tient pas de cela."),
 (646.5,  "Oui ? Il y a ceux qui tiennent comme le Ran, que déplacer du mouktsé pour le besoin du mouktsé est interdit ; alors parfois"),
 (653.2,  "on t'apporte un argument supplémentaire pour l'indulgence : que tu tiens déjà le mouktsé [en main], donc tu peux continuer avec lui, par exemple. Mais"),
 (658.7,  "on le voit bien, à plusieurs endroits chez l'Admour Hazaken — et c'est sa conclusion —, que déplacer du mouktsé"),
 (669.8,  "begufo, même si c'est la manière [habituelle], tant que le problème du déplacement se situe dans les mains... On le voit à plusieurs endroits ; regardez-les tous, vous arriverez à la même"),
 (678.5,  "conclusion : le problème, c'est dans les mains. Et au passage, c'est donc"),
 (684.2,  "un point important, car le point du 'Hazon Ich, tout à l'heure, c'est qu'effectivement il y en a un peu qui sont stricts, mais le monde [la majorité] est indulgent ; car lui est vraiment allé vers la rigueur, en disant"),
 (694.0,  "que c'est permis seulement quand il n'apparaît pas que tu déplaces. Mais pour le besoin du mouktsé et en le visant, c'est certainement un problème [selon lui]."),
 (699.9,  "Mais dire que cela s'appelle un tiltoul..."),
 (704.8,  "en fait, le tiltoul ordinaire begufo — qui est la façon de le déplacer, comme une personne prendrait ce mouktsé ainsi —"),
 (712.2,  "oui, il y a des choses que tu déplaces avec le dos de la main."),
 (716.0,  "Oui. Donc prétendre que cela s'appellerait un tiltoul [ordinaire, interdit] et non un begufo — non, ce n'est pas ainsi qu'on tranche. Beaucoup sont stricts, mais nous, nous devons être indulgents : c'est un tiltoul begufo."),
 (727.2,  "Et même quand l'Admour Hazaken parle de « ses mains » [il situe l'interdit dans les mains], c'est par crainte que tu le prennes et le poses à la main. Voilà donc, en fait, le point."),
 (735.2,  "On peut le voir au siman [311] séif 19, et à quelques autres endroits — regardez dans les notes là-bas."),
 (740.7,  "Il y a [le siman] 276,"),
 (742.5,  "à l'alinéa du Kountrass A'haron, il y en a plusieurs ; il y a, au siman [311], l'alinéa 10, il y a plusieurs Kountrass A'haron. Mais c'est la conclusion."),
 (750.2,  "— Le déplacement avec le dos de la main."),
 (751.7,  "— Ah oui, parlons donc du tiltoul begav hayad (le déplacement avec le dos de la main)."),
 (755.5,  "Le déplacement avec le dos de la main : d'abord, la conclusion de l'Admour Hazaken, c'est que cela s'appelle un tiltoul begufo à 100 %,"),
 (761.1,  "avec toutes les permissions pour le besoin du mouktsé ; il n'y a là aucun problème. Où l'écrit-il ? Au siman 276 séif 10. Et celui qui ne lit que le début"),
 (770.8,  "peut s'embrouiller : au début il l'appelle « min hatsad » en quelque sorte, mais à la fin,"),
 (778.6,  "explicitement, il donne l'exemple, au séif 10 : il dit que, quand tu déplaces derrière les mains (mé'a'horei yadav), tu peux déplacer même pour le besoin du mouktsé, derrière les mains, car"),
 (788.7,  "il dit explicitement que c'est un tiltoul begufo, derrière la main. Sauf que là, il n'a pas voulu accorder de le faire entièrement par un non-juif, car ce 'hidouch — faire un chvout dichvout"),
 (799.1,  "hors d'un cas de mitsva, alors que tu pouvais le faire toi-même —"),
 (803.4,  "Rabbenou Tam conteste cette chose : déplacer le mouktsé pour le besoin du mouktsé, là-dessus il conteste."),
 (812.2,  "Donc tu ne peux pas te servir de la permission de Rabbenou Tam, [selon laquelle] une chose que tu peux faire sans chinouï, il peut la faire bechinouï — [ce serait] contre Rabbenou Tam."),
 (821.6,  "Mais regarde à l'intérieur du maamar : au fil du séif 10, c'est clair comme le jour."),
 (827.6,  "Donc il est permis de déplacer derrière les mains. En revanche,"),
 (832.2,  "beaucoup d'A'haronim qui ont étudié aussi la Michna Beroura disent : non — pourquoi est-il écrit « tiltoul min hatsad » ?"),
 (838.3,  "Ils veulent dire que toute la permission est pour le besoin d'une chose permise ; mais pour le besoin d'une chose interdite,"),
 (846.7,  "il n'y a pas de permission derrière les mains. C'est pourquoi ils vont même jusqu'à émettre des réserves — énormément d'A'haronim le soutiennent ainsi : le Chevet Halevi, le Rav Elyashiv, et d'autres ; ils émettent même"),
 (859.0,  "des réserves au sujet du coude (marpek),"),
 (862.2,  "[se demandant] jusqu'où va « ses mains », car ils veulent dire : ne t'occupe pas du mouktsé avec ce membre, la main. Or « la main » n'est pas seulement la dernière partie de la main, ça peut être aussi l'avant-bras ; donc ici"),
 (876.1,  "on pilpoule là-dessus. C'est un peu difficile de faire entrer cela dans la Michna Beroura, car il y a un endroit explicite d'où il ressort que c'est permis."),
 (885.0,  "Au moins pour le coude (marpek), c'est explicite qu'il y a une permission. Mais quand même,"),
 (890.3,  "énormément de Possekim"),
 (892.4,  "sont stricts : ne pas déplacer derrière les mains pour le besoin du mouktsé."),
 (897.6,  "Oui ; en revanche, selon l'avis de l'Admour Hazaken, c'est permis."),
 (902.1,  "Chez l'Admour Hazaken, c'est explicite, au siman 276 séif 10 : même pour le besoin du mouktsé, cela s'appelle en fait un tiltoul begufo. Dernière chose :"),
 (915.1,  "vous vous souvenez du sujet que vous m'avez demandé de vive voix ?"),
 (918.9,  "L'Admour Hazaken écrit —"),
 (921.1,  "c'était au siman 311 séif 8-9, peut-être ; c'était le cas"),
 (930.6,  "de l'exemple du lit, ou comme le couteau,"),
 (935.1,  "où tu déplaces le mouktsé avec le couteau."),
 (939.9,  "Alors, la plupart des compilateurs sont justement indulgents là-dessus : le Shemirat Shabbat KeHilchata écrit que tout mouktsé est dérabbanan, donc,"),
 (947.2,  "puisqu'il y a beaucoup de Possekim qui ne sont pas d'accord avec l'Admour Hazaken [pour dire] que cela s'appelle « yad arichta » (la main prolongée) — oui, tu pousses le mouktsé ainsi avec le couteau —,"),
 (956.2,  "ils disent que ce n'est pas comme soulever une assiette."),
 (959.8,  "Ils disent que l'Admour Hazaken est strict là-dessus, mais beaucoup sont indulgents, et c'est une affaire dérabbanan. Donc voici"),
 (965.4,  "un exemple : si tu as besoin de la place, tu as du mouktsé et tu as un lit — alors ils disent, selon l'Admour Hazaken, c'est [comme] une yad arichta."),
 (973.7,  "La permission qu'on a apprise au passage là [pour le lit] vient du [statut de] geraf chel re'i (le pot qu'on évacue) :"),
 (978.9,  "tu as plein de noix par terre, alors le mouktsé a perdu [son interdit] — il n'y a plus de mouktsé, [comme dans] un geraf chel re'i. Mais il ressort qu'il y aurait bien eu"),
 (987.2,  "un problème si ce n'était pas un geraf chel re'i ; si, pour le lit, ç'avait été un problème — pourquoi ? Parce que c'est une yad arichta —, cela renforce ce que"),
 (993.9,  "l'Admour Hazaken écrit au sujet du couteau. Alors on m'a demandé"),
 (998.3,  "— ici, les 'havrouta m'ont demandé : quelle est la différence avec le tiltoul min hatsad ? Ce n'est pas la même chose, car"),
 (1003.7,  "j'ai dit : tu as, disons, ceci [qui est] du mouktsé et ceci [qui est] une assiette, alors je soulève l'assiette."),
 (1010.2,  "Bon, du coup le mouktsé est déplacé incidemment. Mais ici, je m'occupe de l'assiette,"),
 (1018.2,  "et de manière incidente le mouktsé est aussi déplacé. Tandis qu'ici je m'occupe"),
 (1024.1,  "de déplacer le mouktsé. Oui ? Je le pousse. Alors, quand je le pousse, c'est comme ma main allongée."),
 (1031.9,  "Maintenant, pourquoi est-ce important ? Bon, c'est bien de souligner la rigueur de l'Admour Hazaken là-dessus, mais pourquoi est-ce important ?"),
 (1039.9,  "Eh bien, il y a vraiment une question"),
 (1043.4,  "chaque Yom Tov — et je veux voir ce que vous en dites — quand nous avons allumé les bougies de Chabbat"),
 (1050.9,  "à la sortie du premier jour de Yom Tov — oui, de jour bien sûr, c'était la veille de Chabbat — ou parfois quand tu allumes les bougies"),
 (1056.9,  "du deuxième jour de Yom Tov : il y a souvent des cas où une personne insère"),
 (1064.1,  "une petite bougie (néroun) dans le bougeoir lui-même,"),
 (1068.2,  "et là il arrive que tu veuilles insérer la deuxième bougie et que ce soit coincé ; ou parfois il y a un pic en métal qui ne te laisse pas la possibilité de l'insérer. Alors parfois,"),
 (1082.6,  "ce que tu fais : tu veux prendre un couteau"),
 (1086.5,  "pour enlever un peu de cire, afin de dégager cela."),
 (1091.9,  "La question est : peux-tu faire cela un Yom Tov ? Maintenant, tu vas dire : un instant, mais la bougie, je peux l'allumer un Yom Tov ! Oui."),
 (1101.9,  "Pourquoi puis-je allumer une bougie un Yom Tov, et pourquoi ne pourrais-je pas... comment prends-tu de la cire à la main ?"),
 (1108.0,  "Alors disons ceci :"),
 (1110.5,  "le Chabbat, tu ne peux rien faire de tout cela ; mais disons que ce qui est permis est permis : il est permis d'allumer des bougies un Yom Tov, il est permis d'allumer à partir d'un feu existant — donc il n'y a pas de mouktsé."),
 (1124.7,  "Mais maintenant il y a des résidus de cire. Or, autrefois, on écrivait que ce n'était vraiment pas mouktsé, car tu pouvais encore t'en servir. Aujourd'hui, des gens ont des magasins, ils achètent"),
 (1133.4,  "des tonnes de bougies ; autrefois ce n'était pas ainsi : les gens pouvaient reprendre toute la matière à neuf,"),
 (1140.8,  "parfois tu prends tous les résidus, tu les réchauffes, tu les refabriques, tu insères une mèche à l'intérieur et tu rallumes."),
 (1148.6,  "Mais aujourd'hui, tu ne fais pas cela ; donc, aujourd'hui, il est très possible que les résidus de cire soient mouktsé."),
 (1155.4,  "Tu n'en fais rien, tu ne t'en sers pas pour une autre bougie."),
 (1159.9,  "Alors, si c'est mouktsé, comment le déplaces-tu ?"),
 (1163.3,  "Eh bien, il y a — dans beaucoup d'ouvrages ; il y a dans le Chevach HaMoadim —"),
 (1168.9,  "je me souviens qu'il a écrit là-dessus :"),
 (1173.2,  "il a écrit qu'il y en a qui veulent dire que ce n'est pas mouktsé du tout, car c'est comme permis — tu as le droit d'allumer des bougies, et ce résidu te prend la place, donc cela fait partie de l'affaire. Mais un instant, il y a"),
 (1187.6,  "d'autres solutions : tu pouvais prendre de petites bougies (néronim) que tu poses sur le bougeoir, et même les éjecter bechinouï (de manière inhabituelle),"),
 (1195.3,  "oui, ou les prendre par-derrière. Il y a des solutions."),
 (1200.6,  "Alors, c'est comme un mékhchir [un accessoire] : ici, c'est quelque chose que tu dois faire en préparation, mais tu n'es pas obligé de passer par ce moyen-là. Donc"),
 (1210.5,  "alors il dit : même si c'est mouktsé,"),
 (1213.5,  "ce n'est pas un problème,"),
 (1216.0,  "car en fait tu le prends par le moyen d'autre chose ; ainsi il écrit là, oui, que tu le prends avec... que tu le pousses avec le couteau."),
 (1224.4,  "Donc c'est en ordre."),
 (1227.1,  "Et plein de compilateurs — dans le Piskei Teshouvot aussi, je l'ai vu — écrivent ainsi : même si c'est mouktsé, c'est un maniement par le moyen d'autre chose. Mais ce n'est pas évident selon l'avis de l'Admour Hazaken,"),
 (1235.5,  "car quand je prends le couteau ici, il est clair que j'ai l'intention de m'occuper de ce qui se passe ici avec le couteau. Oui,"),
 (1244.2,  "ce n'est pas seulement que je"),
 (1247.3,  "veux soulever quelque chose : j'ai juste besoin de pousser un peu, j'ai besoin de jouer avec, comme ma main"),
 (1253.8,  "qui s'occupe de cela."),
 (1256.0,  "C'est pourquoi je préfère dire aux femmes :"),
 (1260.3,  "un Yom Tov, il y a toutes sortes de solutions ; parfois il y en a comme ça — soit prendre de petites bougies et les éjecter ; on peut aussi insérer même ce genre de bougies"),
 (1271.7,  "dans une coupelle en aluminium qu'on peut jeter et que tu remplaces — oui, sortir cela bechinouï ;"),
 (1278.8,  "même si, disons, c'est mouktsé, tu poses autre chose. Mais sortir cela ainsi [avec le couteau], à mon avis — si l'Admour Hazaken n'a pas pensé à ce cas-là, au sujet du couteau — êtes-vous d'accord avec moi ?"),
 (1290.0,  "— Le récipient du feu, un Yom Tov : ne peut-on pas dire que ce bougeoir est... est-il mouktsé ou non ?"),
 (1296.8,  "— Mais disons ceci : il est permis d'allumer des bougies un Yom Tov ; donc, un Yom Tov, tu veux y voir dans ta chambre, tu prends le bougeoir."),
 (1307.1,  "Le Chabbat, c'est mouktsé, toute l'affaire."),
 (1308.5,  "— Alors, le récipient sur lequel se trouve"),
 (1310.4,  "la bougie elle-même, comment le définit-on ?"),
 (1313.3,  "— Un Yom Tov, comme c'est un besoin entièrement permis, il n'est pas devenu mouktsé — pas mouktsé du tout."),
 (1320.8,  "— Mais le résidu de cire qui reste, là, dont tu ne te sers pas non plus :"),
 (1324.1,  "c'est comme les résidus de quelque chose, alors cela peut bien être mouktsé. Bon. Okay."),
]

def fmt(t, sep):
    h = int(t // 3600)
    m = int((t % 3600) // 60)
    s = int(t % 60)
    ms = int(round((t - int(t)) * 1000))
    if ms == 1000:
        s += 1; ms = 0
    return f"{h:02d}:{m:02d}:{s:02d}{sep}{ms:03d}"

srt, vtt = [], ["WEBVTT", ""]
for i, (start, text) in enumerate(cues):
    end = cues[i+1][0] if i+1 < len(cues) else VIDEO_END
    assert end > start, f"cue {i+1}: end <= start ({start} -> {end})"
    srt.append(str(i+1))
    srt.append(f"{fmt(start,',')} --> {fmt(end,',')}")
    srt.append(text)
    srt.append("")
    vtt.append(f"{fmt(start,'.')} --> {fmt(end,'.')}")
    vtt.append(text)
    vtt.append("")

open("chiour4_fr.srt", "w", encoding="utf-8").write("\n".join(srt))
open("chiour4_fr.vtt", "w", encoding="utf-8").write("\n".join(vtt))
print(f"OK — {len(cues)} sous-titres écrits (chiour4_fr.srt + chiour4_fr.vtt)")
