import { DatabaseSync } from 'node:sqlite';

export class EditorialRegistry {
  constructor(path = process.env.RAV_CONTENT_REGISTRY_PATH) {
    if (!path) throw new Error('RAV_CONTENT_REGISTRY_PATH is required');
    this.db = new DatabaseSync(path);
    this.db.exec(`PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS content_candidates (candidate_id TEXT PRIMARY KEY, candidate_public_id TEXT UNIQUE NOT NULL, source_type TEXT NOT NULL, source_internal_id TEXT NOT NULL, topic TEXT, reliability_level TEXT NOT NULL, editorial_status TEXT NOT NULL, privacy_risk TEXT NOT NULL, duplicate_score INTEGER NOT NULL DEFAULT 0, editorial_score INTEGER NOT NULL DEFAULT 0, payload_json TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS editorial_usage (id INTEGER PRIMARY KEY, candidate_id TEXT NOT NULL, topic TEXT, angle TEXT, platform TEXT, format TEXT, publication_date TEXT, status TEXT, campaign TEXT, performance_json TEXT, recycle_after TEXT); CREATE TABLE IF NOT EXISTS validations (id INTEGER PRIMARY KEY, candidate_id TEXT NOT NULL, reviewer TEXT, decision TEXT NOT NULL, notes TEXT, date TEXT NOT NULL); CREATE TABLE IF NOT EXISTS transcript_versions (id INTEGER PRIMARY KEY, candidate_id TEXT NOT NULL, original_text TEXT NOT NULL, working_text TEXT, validated_text TEXT, reviewer TEXT, notes TEXT, created_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS source_checks (id INTEGER PRIMARY KEY, candidate_id TEXT NOT NULL, reference TEXT, status TEXT NOT NULL, notes TEXT, checked_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS media_jobs (id INTEGER PRIMARY KEY, candidate_id TEXT UNIQUE NOT NULL, video_source TEXT, audio_source TEXT, start_time INTEGER, end_time INTEGER, formats_json TEXT NOT NULL, subtitle_text TEXT, hook TEXT, title TEXT, status TEXT NOT NULL, outputs_json TEXT, error TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS scheduled_content (id INTEGER PRIMARY KEY, candidate_id TEXT NOT NULL, platform TEXT, recommended_time TEXT, scheduled_at TEXT, status TEXT NOT NULL); CREATE TABLE IF NOT EXISTS performance (id INTEGER PRIMARY KEY, candidate_id TEXT NOT NULL, platform TEXT, post_id TEXT, views INTEGER, reach INTEGER, likes INTEGER, comments INTEGER, shares INTEGER, saves INTEGER, watch_time INTEGER, followers_gained INTEGER);`);
  }
  close() { this.db.close(); }
  recentUsage(topic) { return this.db.prepare('SELECT * FROM editorial_usage WHERE topic = ? ORDER BY publication_date DESC LIMIT 20').all(topic || ''); }
  duplicateScore(candidate) { const usage = this.recentUsage(candidate.topic); if (usage.some((u) => u.candidate_id === candidate.candidate_id)) return 100; if (usage.some((u) => u.angle === candidate.angle)) return 70; return usage.length ? 35 : 0; }
  saveCandidate(candidate) { const now = new Date().toISOString(); this.db.prepare(`INSERT INTO content_candidates VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT(candidate_id) DO UPDATE SET payload_json=excluded.payload_json, reliability_level=excluded.reliability_level, editorial_status=excluded.editorial_status, privacy_risk=excluded.privacy_risk, duplicate_score=excluded.duplicate_score, editorial_score=excluded.editorial_score, updated_at=excluded.updated_at`).run(candidate.candidate_id, candidate.candidate_public_id, candidate.source_type, String(candidate.source_internal_id), candidate.topic, candidate.reliability_level, candidate.editorial_status, candidate.privacy_risk, candidate.duplicate_score, candidate.editorial_score, JSON.stringify(candidate), now, now); }
  candidate(id) { const row = this.db.prepare('SELECT * FROM content_candidates WHERE candidate_id=?').get(id); return row ? { ...row, payload: JSON.parse(row.payload_json) } : null; }
  candidates(status) { const rows = this.db.prepare(status ? 'SELECT * FROM content_candidates WHERE editorial_status=? ORDER BY editorial_score DESC' : 'SELECT * FROM content_candidates ORDER BY editorial_score DESC').all(...(status ? [status] : [])); return rows.map((row) => ({ ...row, payload: JSON.parse(row.payload_json) })); }
  saveTranscriptVersion(candidateId, original, working, validated, reviewer, notes = '') { this.db.prepare('INSERT INTO transcript_versions (candidate_id, original_text, working_text, validated_text, reviewer, notes, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)').run(candidateId, original, working, validated, reviewer || 'local-reviewer', notes, new Date().toISOString()); }
  validate(candidateId, reviewer, decision, notes = '', options = {}) { if (!['APPROVED', 'NEEDS_CORRECTION', 'REJECTED', 'DEFERRED'].includes(decision)) throw new Error('Invalid decision'); const record = this.candidate(candidateId); if (!record) throw new Error('Candidate not found'); const c = record.payload; if (decision === 'APPROVED' && (c.reliability_level === 'RED' || c.privacy_risk === 'BLOCKED' || !c.provenance)) throw new Error('Candidate cannot be approved'); if (options.validated_transcript) { this.saveTranscriptVersion(candidateId, c.rav_exact_text, c.rav_clean_text, options.validated_transcript, reviewer, notes); c.validated_transcript = options.validated_transcript; c.rav_clean_text = options.validated_transcript; }
    if (options.quote_verified) c.quote_verified = true; if (options.source_checks) c.halakhic_sources_verified = options.source_checks.every((x) => x.status === 'verified'); if (decision === 'APPROVED' && c.privacy_risk !== 'BLOCKED') c.reliability_level = 'GREEN'; c.editorial_status = decision; this.db.prepare('INSERT INTO validations (candidate_id, reviewer, decision, notes, date) VALUES (?, ?, ?, ?, ?)').run(candidateId, reviewer || 'local-reviewer', decision, notes, new Date().toISOString()); this.db.prepare('UPDATE content_candidates SET editorial_status=?, reliability_level=?, payload_json=?, updated_at=? WHERE candidate_id=?').run(decision, c.reliability_level, JSON.stringify(c), new Date().toISOString(), candidateId); }
  createMediaJob(candidate) { if (candidate.reliability_level === 'RED') throw new Error('RED_MEDIA_JOB_BLOCKED'); if (candidate.editorial_status !== 'APPROVED') throw new Error('MEDIA_REQUIRES_APPROVAL'); const now = new Date().toISOString(); this.db.prepare('INSERT INTO media_jobs (candidate_id, video_source, audio_source, start_time, end_time, formats_json, subtitle_text, hook, title, status, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT(candidate_id) DO NOTHING').run(candidate.candidate_id, candidate.video_source || null, candidate.audio_reference || null, candidate.audio_start || 0, candidate.audio_end || null, JSON.stringify(candidate.formats || []), candidate.validated_transcript || candidate.rav_clean_text, candidate.hook, candidate.topic, 'DRAFT', now, now); return this.db.prepare('SELECT * FROM media_jobs WHERE candidate_id=?').get(candidate.candidate_id); }
  updateMediaJob(id, status, outputs = {}, error = null) { this.db.prepare('UPDATE media_jobs SET status=?, outputs_json=?, error=?, updated_at=? WHERE id=?').run(status, JSON.stringify(outputs), error, new Date().toISOString(), id); }
}
