import { DatabaseSync } from 'node:sqlite';

export class EditorialRegistry {
  constructor(path = process.env.RAV_CONTENT_REGISTRY_PATH) {
    if (!path) throw new Error('RAV_CONTENT_REGISTRY_PATH is required');
    this.db = new DatabaseSync(path);
    this.db.exec(`PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS content_candidates (candidate_id TEXT PRIMARY KEY, candidate_public_id TEXT UNIQUE NOT NULL, source_type TEXT NOT NULL, source_internal_id TEXT NOT NULL, topic TEXT, reliability_level TEXT NOT NULL, editorial_status TEXT NOT NULL, privacy_risk TEXT NOT NULL, duplicate_score INTEGER NOT NULL DEFAULT 0, editorial_score INTEGER NOT NULL DEFAULT 0, payload_json TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS editorial_usage (id INTEGER PRIMARY KEY, candidate_id TEXT NOT NULL, topic TEXT, angle TEXT, platform TEXT, format TEXT, publication_date TEXT, status TEXT, campaign TEXT, performance_json TEXT, recycle_after TEXT); CREATE TABLE IF NOT EXISTS validations (id INTEGER PRIMARY KEY, candidate_id TEXT NOT NULL, reviewer TEXT, decision TEXT NOT NULL, notes TEXT, date TEXT NOT NULL); CREATE TABLE IF NOT EXISTS scheduled_content (id INTEGER PRIMARY KEY, candidate_id TEXT NOT NULL, platform TEXT, scheduled_at TEXT, status TEXT NOT NULL); CREATE TABLE IF NOT EXISTS performance (id INTEGER PRIMARY KEY, candidate_id TEXT NOT NULL, platform TEXT, post_id TEXT, views INTEGER, reach INTEGER, likes INTEGER, comments INTEGER, shares INTEGER, saves INTEGER, watch_time INTEGER, followers_gained INTEGER);`);
  }
  close() { this.db.close(); }
  recentUsage(topic) { return this.db.prepare('SELECT * FROM editorial_usage WHERE topic = ? ORDER BY publication_date DESC LIMIT 20').all(topic || ''); }
  duplicateScore(candidate) { const usage = this.recentUsage(candidate.topic); if (usage.some((u) => u.candidate_id === candidate.candidate_id)) return 100; if (usage.some((u) => u.angle === candidate.angle)) return 70; return usage.length ? 35 : 0; }
  saveCandidate(candidate) { const now = new Date().toISOString(); this.db.prepare(`INSERT INTO content_candidates VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT(candidate_id) DO UPDATE SET payload_json=excluded.payload_json, reliability_level=excluded.reliability_level, editorial_status=excluded.editorial_status, privacy_risk=excluded.privacy_risk, duplicate_score=excluded.duplicate_score, editorial_score=excluded.editorial_score, updated_at=excluded.updated_at`).run(candidate.candidate_id, candidate.candidate_public_id, candidate.source_type, String(candidate.source_internal_id), candidate.topic, candidate.reliability_level, candidate.editorial_status, candidate.privacy_risk, candidate.duplicate_score, candidate.editorial_score, JSON.stringify(candidate), now, now); }
  validate(candidateId, reviewer, decision, notes = '') { if (!['APPROVED', 'NEEDS_CORRECTION', 'REJECTED'].includes(decision)) throw new Error('Invalid decision'); this.db.prepare('INSERT INTO validations (candidate_id, reviewer, decision, notes, date) VALUES (?, ?, ?, ?, ?)').run(candidateId, reviewer || 'local-reviewer', decision, notes, new Date().toISOString()); this.db.prepare('UPDATE content_candidates SET editorial_status=?, updated_at=? WHERE candidate_id=?').run(decision, new Date().toISOString(), candidateId); }
}
