"""schema initial — quatorze tables du cahier des charges

Revision ID: dbb6179514a1
Revises: 
Create Date: 2026-07-28 14:27:26.090491
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dbb6179514a1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('alerts_total', sa.Integer(), nullable=False),
    sa.Column('validated_total', sa.Integer(), nullable=False),
    sa.Column('rejected_total', sa.Integer(), nullable=False),
    sa.Column('false_positives_total', sa.Integer(), nullable=False),
    sa.Column('autocorrect_allowed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('crawl_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'done', 'failed', name='crawl_job_status'), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=True),
    sa.Column('pages_total', sa.Integer(), nullable=False),
    sa.Column('pages_ok', sa.Integer(), nullable=False),
    sa.Column('pages_failed', sa.Integer(), nullable=False),
    sa.Column('pages_changed', sa.Integer(), nullable=False),
    sa.Column('pages_missing', sa.Integer(), nullable=False),
    sa.Column('broken_links', sa.Integer(), nullable=False),
    sa.Column('log', sa.Text(), nullable=True, comment='Journal détaillé par page, JSON'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('siman', sa.Integer(), nullable=True),
    sa.Column('langue', sa.String(length=8), nullable=False),
    sa.Column('niveau', sa.String(length=32), nullable=False),
    sa.Column('titre', sa.String(length=500), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('redirect_target', sa.String(length=500), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modified_at', sa.DateTime(timezone=True), nullable=True, comment='Dernière date où un changement de contenu a été détecté'),
    sa.Column('current_text_sha256', sa.String(length=64), nullable=True),
    sa.Column('audit_status', sa.Enum('new', 'crawled', 'changed', 'missing', 'error', name='page_audit_status'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pages_current_text_sha256'), ['current_text_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_pages_siman'), ['siman'], unique=False)
        batch_op.create_index(batch_op.f('ix_pages_url'), ['url'], unique=True)

    op.create_table('source_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('base_url', sa.String(length=300), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('rate_limit_seconds', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('source_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('ref', sa.String(length=300), nullable=False),
    sa.Column('lang', sa.String(length=8), nullable=True),
    sa.Column('version_title', sa.String(length=300), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_texts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_texts_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_texts_ref'), ['ref'], unique=False)

    op.create_table('terminology_dictionary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical', sa.String(length=120), nullable=False),
    sa.Column('variants', sa.Text(), nullable=True, comment='Variantes acceptées, JSON'),
    sa.Column('forbidden_variants', sa.Text(), nullable=True, comment='Variantes interdites, JSON'),
    sa.Column('lang', sa.String(length=8), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical')
    )
    op.create_table('page_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('html_raw', sa.Text(), nullable=True),
    sa.Column('text_clean', sa.Text(), nullable=True),
    sa.Column('html_sha256', sa.String(length=64), nullable=True),
    sa.Column('text_sha256', sa.String(length=64), nullable=True),
    sa.Column('is_change', sa.Boolean(), nullable=False, comment='False pour la première collecte, True pour un changement détecté ensuite'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('page_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_versions_page_id'), ['page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_versions_text_sha256'), ['text_sha256'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=120), nullable=True, comment='NULL = action système'),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('text_before', sa.Text(), nullable=True),
    sa.Column('text_after', sa.Text(), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('page_version_id', sa.Integer(), nullable=True),
    sa.Column('rule_version', sa.String(length=32), nullable=True),
    sa.Column('previous_status', sa.String(length=40), nullable=True),
    sa.Column('new_status', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['page_version_id'], ['page_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)

    op.create_table('content_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_version_id', sa.Integer(), nullable=False),
    sa.Column('stable_id', sa.String(length=64), nullable=False, comment='Ex. OH-268-BASE-FR-P014 — stable entre versions proches'),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.Enum('titre', 'sous_titre', 'paragraphe', 'citation_hebraique', 'traduction', 'source', 'liste', 'tableau', 'cas_pratique', 'resume', 'conclusion', 'quiz', 'note', name='block_type'), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('normalized_content', sa.Text(), nullable=True),
    sa.Column('css_selector', sa.String(length=500), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['page_version_id'], ['page_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_version_id', 'stable_id')
    )
    with op.batch_alter_table('content_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_blocks_page_version_id'), ['page_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_blocks_stable_id'), ['stable_id'], unique=False)

    op.create_table('audit_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('subcategory', sa.String(length=64), nullable=True),
    sa.Column('current_text', sa.Text(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('proposed_correction', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('sources', sa.Text(), nullable=True, comment='Références des sources, JSON ou texte'),
    sa.Column('confidence', sa.Float(), nullable=True, comment='0.0 – 1.0'),
    sa.Column('severity', sa.Enum('P0_CRITICAL', 'P1_MAJOR', 'P2_SIGNIFICANT', 'P3_MINOR', 'P4_SUGGESTION', name='severity'), nullable=False),
    sa.Column('risk', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'HALAKHIC', name='risk'), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'AUTOMATICALLY_ANALYZED', 'ADMIN_REVIEW_REQUIRED', 'EDITOR_APPROVED', 'RABBINIC_REVIEW_REQUIRED', 'RABBINIC_APPROVED', 'REJECTED', 'FALSE_POSITIVE', 'EDITORIAL_VARIANT', 'SOURCE_UNAVAILABLE', 'READY_FOR_STAGING', 'PUBLISHED', 'CLOSED', name='finding_status'), nullable=False),
    sa.Column('rule_code', sa.String(length=64), nullable=True),
    sa.Column('rule_version', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['content_blocks.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_findings_block_id'), ['block_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_findings_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_findings_page_id'), ['page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_findings_risk'), ['risk'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_findings_rule_code'), ['rule_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_findings_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_findings_status'), ['status'], unique=False)

    op.create_table('parsed_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('work', sa.String(length=120), nullable=True, comment='Ouvrage/auteur normalisé'),
    sa.Column('section', sa.String(length=120), nullable=True),
    sa.Column('siman', sa.String(length=16), nullable=True),
    sa.Column('seif', sa.String(length=16), nullable=True),
    sa.Column('seif_katan', sa.String(length=16), nullable=True),
    sa.Column('daf', sa.String(length=16), nullable=True),
    sa.Column('amud', sa.String(length=4), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('span_start', sa.Integer(), nullable=True),
    sa.Column('span_end', sa.Integer(), nullable=True),
    sa.Column('validation_status', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['content_blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parsed_references', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parsed_references_block_id'), ['block_id'], unique=False)

    op.create_table('admin_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('source_attached', sa.Text(), nullable=True),
    sa.Column('previous_status', sa.String(length=40), nullable=True),
    sa.Column('new_status', sa.String(length=40), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['audit_findings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_decisions_finding_id'), ['finding_id'], unique=False)

    op.create_table('rabbinic_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('reviewer', sa.String(length=120), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('asked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['audit_findings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rabbinic_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rabbinic_reviews_finding_id'), ['finding_id'], unique=False)

    op.create_table('suggested_corrections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('text_before', sa.Text(), nullable=True),
    sa.Column('text_after', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('applied', sa.Boolean(), nullable=False, comment='Toujours False en Phase 1 : aucune application automatique'),
    sa.ForeignKeyConstraint(['finding_id'], ['audit_findings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suggested_corrections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suggested_corrections_finding_id'), ['finding_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suggested_corrections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suggested_corrections_finding_id'))

    op.drop_table('suggested_corrections')
    with op.batch_alter_table('rabbinic_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rabbinic_reviews_finding_id'))

    op.drop_table('rabbinic_reviews')
    with op.batch_alter_table('admin_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_decisions_finding_id'))

    op.drop_table('admin_decisions')
    with op.batch_alter_table('parsed_references', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parsed_references_block_id'))

    op.drop_table('parsed_references')
    with op.batch_alter_table('audit_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_findings_status'))
        batch_op.drop_index(batch_op.f('ix_audit_findings_severity'))
        batch_op.drop_index(batch_op.f('ix_audit_findings_rule_code'))
        batch_op.drop_index(batch_op.f('ix_audit_findings_risk'))
        batch_op.drop_index(batch_op.f('ix_audit_findings_page_id'))
        batch_op.drop_index(batch_op.f('ix_audit_findings_category'))
        batch_op.drop_index(batch_op.f('ix_audit_findings_block_id'))

    op.drop_table('audit_findings')
    with op.batch_alter_table('content_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_blocks_stable_id'))
        batch_op.drop_index(batch_op.f('ix_content_blocks_page_version_id'))

    op.drop_table('content_blocks')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('page_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_versions_text_sha256'))
        batch_op.drop_index(batch_op.f('ix_page_versions_page_id'))

    op.drop_table('page_versions')
    op.drop_table('terminology_dictionary')
    with op.batch_alter_table('source_texts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_texts_ref'))
        batch_op.drop_index(batch_op.f('ix_source_texts_provider'))

    op.drop_table('source_texts')
    op.drop_table('source_providers')
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pages_url'))
        batch_op.drop_index(batch_op.f('ix_pages_siman'))
        batch_op.drop_index(batch_op.f('ix_pages_current_text_sha256'))

    op.drop_table('pages')
    op.drop_table('crawl_jobs')
    op.drop_table('audit_rules')
    # ### end Alembic commands ###
